stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
Fix for https://github.com/jfrog/charts/issues/15
=> [stable/artifactory][stable/artifactory-ha] Fixing Nginx SecurityContext

stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/nginx-service.yaml
Add annotations configuration for artifactory-ha Helm chart like it already is the case in artifactory Helm chart
Update README.md file with new option.
=> Add nginx service annotations

stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-binarystore.yaml
Fix endpoint and scheme values for AWS S3 provider
#19
=> Fix binarystore for S3 provider

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/values.yaml
Change Distribution DB name to distribution
=> Change Distribution DB name to distribution

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/charts/elasticsearch/templates/elasticsearch-deployment.yaml, stable/mission-control/charts/elasticsearch/values.yaml, stable/mission-control/templates/insight-executor-deployment.yaml, stable/mission-control/templates/insight-scheduler-deployment.yaml, stable/mission-control/templates/mission-control-deployment.yaml, stable/mission-control/values.yaml
Add ability to set Java `Xms` and `Xmx` in the helm chart's values.
=> MC control insight jvm memory

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/values.yaml
Allow setting `replicaCount` per service.
=> Xray per service replicaCount

.gitignore, Makefile, README.md, test/chart_test.sh, test/chartlib.sh, test/e2e-docker4mac.sh, test/e2e-gke.sh, test/e2e-local-gke.sh, test/lint-charts.sh
To speed up local charts testing, remote GKE cluster option was added
=> add option to test charts in remote GKE cluster

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> Set Xray version 2.3.3

Makefile, README.md, test/chart_test.sh, test/chartlib.sh, test/e2e-github.sh, test/e2e-local-gke.sh
revert back to `gcr.io/kubernetes-charts-ci/test-image`
=> fix: e2e-local-gke

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ci/test-values.yaml
Add ci/test-values.yaml for minikube
=> chart: artifactory-ha v0.4.7

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ci/test-values.yaml
Add ci/test-values.yaml to suite minikube
=> chart: artifactory v7.4.3

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/ci/test-values.yaml
* Disable persistence for CI testing for minikube
* Enable RBAC
=> chart: distribution v1.0.1

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/values.yaml
Support Xray nodeSelector, affinity and tolerations.
=> Xray nodeselector affinity tolerations

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/ci/test-values.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/templates/distributor-statefulset.yaml, stable/distribution/templates/redis-statefulset.yaml, stable/distribution/values.yaml
Add nodeSelector, affinity and tolerations for Distribution chart
=> Add nodeselector, affinity and tolerations for Distribution

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.4.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
Add note about 'helm repo add jfrog https://charts.jfrog.io' to all READMEs.
=> Add note about 'helm repo add jfrog https://charts.jfrog.io'

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
Add missing Artifactory PostgreSQL resources template
=> Artifactory postgresql resources template

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml
=> Distribution version 1.3.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
=> Artifactory version 6.5.0

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> Xray version 2.4.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-binarystore.yaml, stable/artifactory-ha/values.yaml
Make artifactory ha S3 endpoint configurable.
This fixes https://github.com/jfrog/charts/issues/82.
=> Make artifactory ha S3 endpoint configurable

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/ci/test-values.yaml, stable/mission-control/requirements.lock, stable/mission-control/requirements.yaml, stable/mission-control/values.yaml
JFMC MongoDB version (chart 4.3.10, app 3.6.8).
Related to https://github.com/jfrog/charts/issues/70
=> JFMC MongoDB version (chart 4.3.10, app 3.6.8)

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/requirements.lock, stable/distribution/requirements.yaml, stable/distribution/values.yaml
Distribution MongoDB version (chart 4.3.10, app 3.6.8).
Related to #70.
=> Distribution MongoDB version (chart 4.3.10, app 3.6.8)

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/ci/test-values.yaml, stable/mission-control/templates/mission-control-certs.yaml, stable/mission-control/templates/mission-control-deployment.yaml, stable/mission-control/values.yaml
=> Fixes #67 Insight password verification failed

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> Xray version 2.4.1

LICENSE, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/LICENSE, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/LICENSE, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/LICENSE, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/LICENSE, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/LICENSE
Add Apache 2.0 license file.
Resolve #79.
=> Add Apache 2.0 license file

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.5.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/NOTES.txt, stable/artifactory-ha/templates/artifactory-binarystore.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/artifactory-secrets.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-secrets.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Appian is currently deploying a customized variant of the `stable/artifactory-ha` chart for production use. This PR incorporates changes we've needed to make to suit our CD workflow. See the changelog and commit history for more details. Some commits only apply to the `stable/artifactory-ha` chart. These commits are indicated by sentences in the commit message
=> Enhancements to stable/artifactory-ha and stable/artifactory

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.5.2

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/ingress.yaml
@eldada @jainishshah17 
The current annotation support in the ingress templates iterates over items, which breaks certain concepts like configuration-snippets.
This enables the annotation section to be passed in verbatim (or omitted altogether).
No existing issue number, however it is tied to an internal jfrog support ticket.
By doing this, it introduces a warning from lint:
`2018/10/17 14:27:13 warning: destination for annotations is a table. Ignoring non-table value <nil>`
In my research (including talking to people on the #helm-users slack channel), …
=> ingress annotation changes specifially to support docker registry

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/nginx-service.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/nginx-service.yaml, stable/artifactory/values.yaml
Allow user to configure externalTrafficPolicy for Loadbalancer
=> Allow user to configure externalTrafficPolicy for Loadbalancer

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
This fixes a minor bug in the logic that was added to enable providing an external secret for external database credentials that was introduced by https://github.com/jfrog/charts/pull/93
=> Fix external database secret

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/requirements.lock, stable/xray/requirements.yaml, stable/xray/values.yaml
Update postgresql chart version to 0.9.5 so to be able and use the `postgresConfig` parameter.
=> Update postgresql chart version to 0.9.5

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray version 2.4.2

README.md
Remove note about proxying remote as it's not done anymore.
=> Remove note about proxying remote as it's not done anymore

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/templates/xray-setup-conf.yaml
Replace POSTGRESS_ with POSTGRES_ (remove double S).
Just fixing a typo.
=> Replace POSTGRESS_ with POSTGRES_ (remove double S)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Set Xray version 2.4.6

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.5.3

.github/PULL_REQUEST_TEMPLATE.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml
=> Fix location of nodeSelector, affinity and tolerations in the templates

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/templates/distributor-statefulset.yaml, stable/distribution/templates/redis-statefulset.yaml
Fix indent of nodeSelector, affinity and tolerations in the templates
=> Fix indent of nodeSelector, affinity and tolerations in the templates

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.5.8

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> Fix bad example in xray README (#127)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
Upgrade PostgreSQL image version to 9.6.11
=> Artifactory PostgreSQL image version 9.6.11

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.5.9

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Fix #136 
The instructions for creating and using Distribution certificates are not needed. They also don't work.
Removed them.
=> Remove distribution-certs. This is not needed and is confusing.

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-binarystore.yaml
Do not set AWS S3 binary provider `identity` and `credential` if not passed. This will allow using the IAM role.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #134 
=> Make aws identity and credential optional to allow using IAM role

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/external-mongodb-secret.yaml, stable/xray/templates/external-postgres-secret.yaml, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml
Fix for https://github.com/jfrog/charts/issues/73
=> Use secret for external Database

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml
fix the artifactory chart when using exist pvc.
fixes #34 
=> fix existingClaim for artifactory

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #135
=> Fix documentation about Artifactory license setup using secret

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/README.md, stable/kubexray/values.yaml
- Add the `whitelistNamespaces` to all scan policies
- Fix errors in README
- Changing `jfrog-docker-reg2.bintray.io/kubexray` to `docker.bintray.io/kubexray` (they are the same)
=> Add  to all policies and fix some errors in README.md

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/charts/elasticsearch/values.yaml
=> Mission Control version 3.3.2

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.5.13

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/ci/test-values.yaml, stable/distribution/requirements.lock, stable/distribution/requirements.yaml, stable/distribution/templates/database-secrets.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/templates/distributor-statefulset.yaml, stable/distribution/values.yaml
Upgrade Distribution to 1.4.0
- Migration to PostgreSQL as database
- Upgrade by deploying MongoDB and PostgreSQL (`--set mongodb.enabled=true`)
=> Distribution version 1.4.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.6.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.6.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
1. Artifactory version 6.6.3
2. Add support new environment variables that are supported in the new version
=> Artifactory version 6.6.3 and support new environment variables.

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray version 2.6.0

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/ci/test-values.yaml, stable/distribution/requirements.lock, stable/distribution/requirements.yaml, stable/distribution/templates/_helpers.tpl, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
=> Distribution version 1.5.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory version 6.6.5

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml
adding the master key as env var will create the corresponding file in each pod on first start.
=> add master key as env var in Distribution

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml
Copy replicator.yaml to /replicator_extra_conf which copy to its final location by entrypoint.
This is a better way to init replicator.
=> Copy replicator.yaml to /replicator_extra_conf which copy to its final location

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/ingress.yaml, stable/artifactory/values.yaml
This is needed in case of running multiple ingress deployments concurrently. One Deployment deal with internal and another one with external traffic. 
In my case it is need for Traefik Ingress Controller:
https://docs.traefik.io/user-guide/kubernetes/
I have decided to create PR instead of Issue )
We are planning to move our Artifactory Pro to kubernetes and we need this changes to not break existing configuration of our Ingress controller. I hope it can be usefull for …
=> Added values ingress.labels to be able to use labelSelector 

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/values.yaml
Add support for extra custom init containers to allow custom bootstrapping and special setups.
=> Add support for xray extra custom init containers

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Adding support for extra custom init containers that are useful for special dedicated bootstrapping.
**Note**: Once this PR is approved and merged, we'll add this to the other charts as well.
=> Add support for Artifactory extra custom init containers

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
Add support for extra init containers for the Distribution pod
=> Add support for extra custom init containers

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/templates/mission-control-deployment.yaml, stable/mission-control/values.yaml
Support adding extra custom init containers to the mission control pod.
=> Jfmc custom init containers

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-binarystore.yaml
Fix support for using Azure Blob Storage as binary provider.
Add support for HA.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #183
=> Add azure blob ha

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.7.2

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray version 2.6.3

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
Update Postgres Image version to 9.6.11
=> Update Postgres Image version to 9.6.11

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
Add instructions on how to deploy Artifactory with embedded Derby
=> Add instructions on how to deploy Artifactory with embedded Derby

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-setup-conf.yaml, stable/xray/values.yaml
Add an option to specify the indexAllBuilds option in xray_config.yaml (https://www.jfrog.com/confluence/display/XRAY/Configuring+Xray#ConfiguringXray-SpecifyingBuildsforAnalysis) and set it to false by default
=> Add an option to index all builds in artifactory

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray version 2.7.0

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/templates/distribution-svc.yaml, stable/distribution/values.yaml
Add support for setting Distribution's service `loadBalancerSourceRanges` (whitelist IP ranges).
=> Add support for Distribution service loadBalancerSourceRanges

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Updating Artifactory version to 6.8.0

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/database-secrets.yaml, stable/distribution/templates/distribution-svc.yaml, stable/distribution/templates/ingress.yaml, stable/distribution/templates/redis-connection-secret.yaml
Add `component` label to missing objects
=> Add 'component' label to missing objects

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
Just add a commented example of the `SERVER_XML_EXTRA_CONNECTOR` usage
Part of Artifactory 6.8.0 new features.
=> Artifactory 6.8.1 and add example of 'SERVER_XML_EXTRA_CONNECTOR' usage

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> Distribution version 1.6.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.8.2

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md
**What this PR does / why we need it**: Updates Mission Control chart details with new database
=> Update missed chart details

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-binarystore.yaml, stable/artifactory-ha/values.yaml
Adds a new configuration item to the S3 configuration. We've found that without this set (even though it is documented as the default) using kms encrypted buckets causes an issue due to the signature not being V4.
=> [stable/artifactory-ha] Add s3AwsVersion to binarystore configuration

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
Adds same logging side cars in #206 to nginx as well
=> feat(artifactory,artifactory-ha): Add logger to nginx

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.8.3

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/templates/config-xray.yaml
=> Fixed typo

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/templates/mission-control-deployment.yaml, stable/mission-control/values.yaml
Adds support for loggers sidecars for any of the logs in the Mission Control pod
=> Add support for logger sidecar containers in JFMC

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/values.yaml
Add support for a logger sidecar container for Xray pods.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #224 
=> Add support for logger sidecar containers in Xray

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.8.4

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Fix the option to use an existing volume claim for artifactory storage
**Which issue this PR fixes**
fixes #232
=> Fix existingClaim option in artifactory chart

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> added comment for Mongo requirements in values.yaml

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.8.6

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.7.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
This PR adds the option to use existing persistent volume claims for Artifactory primary and member nodes
fixes #173
=> artifactory-ha existing pvc

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
**What this PR does / why we need it**: Update Mission Control version to 3.4.3
=> Update mission-control version to 3.4.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml, stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/templates/deployment.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-deployment.yaml, stable/mission-control/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/values.yaml
Move securityContext to container level
fixes #233
=> Move securityContext to container level

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
=> Update Artifactory to 6.8.7, add support for Artifactory-CE for C++

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Remove the restrictive `securityContext` on an init container
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #247
=> Fix issue #247 (init container failing to run)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml, stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/templates/deployment.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-deployment.yaml, stable/mission-control/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-analysis-deployment.yaml, stable/xray/templates/xray-indexer-deployment.yaml, stable/xray/templates/xray-persist-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/values.yaml
Revert the securityContext change since it caused permissions issues
=> Revert 233

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/README.md, stable/kubexray/templates/ingress.yaml, stable/kubexray/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/ingress.yaml, stable/xray/values.yaml
I have added label selector for Xray and KubeXray ingresses, as well as I, did for Artifactory and Artifactory-ha. It needs to support mapping between multiple ingress controllers.
**Which issue this PR fixes**  N/A
This PR is needed for us to deploy Xray and KubeXray to our Kubernetes cluster. 
Thanks in advance!
=> added label selector for Xray and KubeXray ingresses

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml
=> Update Kubexray to v0.1.2

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/ingress.yaml, stable/artifactory/values.yaml
Depending on ingress used, path is interpreted as / or wildcard /*.
GCE ingress or AWS ALB ingress interpret ingress path differently as f.e. nginx ingress.
=> [artifactory] Make ingress path configurable

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Add support for adding custom sidecar containers.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #257
=> [artifactory] Add support for custom sidecar containers

stable/artifactory/Chart.yaml, test/e2e-gke.sh
=> fix GKE CI

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.9.0

.travis.yml, Makefile, README.md, test/e2e-kind.sh, test/lint-scripts.sh
- Add an option to run tests with `kind` locally - `make kind`
- Update `kind` to `v0.2.1`
=> local kind option, update kind to v0.2.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Adds the option to copy a list of files on startup to ARTIFSCTORY_HOME
fixes #181
=> Add the option to copy a list of files to ARTIFACTORY_HOME on startup

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-statefulset.yaml
Fix an error of missing volume in JFMC when `missionControl.persistence=false`
=> Fix error of missing volume for jfmc when missionControl.persistence is false

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
=> Adding support for user plugins in Artifactory

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml
=> bump kubexray version to 0.1.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-installer-info.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-installer-info.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
=> Added installer info

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-networkpolicy.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-networkpolicy.yaml, stable/distribution/values.yaml, stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/templates/networkpolicy.yaml, stable/kubexray/values.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-networkpolicy.yaml, stable/mission-control/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-networkpolicy.yaml, stable/xray/values.yaml
Adds support for network policy to all charts
fixes #69
=> Add network policy support

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml
this is a small changeset that allows templating of extraEnvironmentVariables.
this will support using things like .Values values in extraEnvironmentVariables
=> add support for templated extraEnvironmentVariables

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
Update Mission-Control version to 3.5.1
=> Update mission-control version to 3.5.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.9.1

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-server-svc.yaml, stable/xray/values.yaml
Hi, guys! This PR will add a capability to add Xray server service annotations. In our case, it is needed to create tcp socket load balancer in AWS, because our ingress controller doesn't support that.
Basically, it helps to resolve this issue: 
https://jfrog.com/knowledge-base/how-to-resolve-the-error-could-not-open-websocket-connection-websocket-could-not-find-connection-header-with-token-upgrade/
Will be good if you can merge it fast :) Thanks in advance!
=> Added Xray server service annotations

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
Update the `curl` examples to `wget` as the Artifactory Docker images now have a new base image without `curl`.
=> Change curl examples to wget (Artifactory new base image)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-binarystore.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-binarystore.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
=> Fix for #303

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/templates/xray-setup-conf.yaml, stable/xray/values.yaml
Add support for customizing the xray_config.yaml file using a configmap
=> Add support for customizing the xray_config.yaml file using a configmap

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-setup-conf.yaml, stable/xray/values.yaml
Move the `skipEntLicCheckForCloud: true` parameter to the default config. This should not be edited by user, or Xray services will not start.
=> Xray move parameter

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
There are cases where a user might want to add a custom `volume` + `volumeMount`. This PR adds the `customVolumeMounts` to support this (`customVolumes` already supported).
=> [Artifactory] Add support for customVolumeMounts

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ReverseProxyConfiguration.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ReverseProxyConfiguration.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #293 
=> Fix for issue #293

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
Update Mission-Control version to 3.5.2
=> Update mission-control version to 3.5.2

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ReverseProxyConfiguration.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ReverseProxyConfiguration.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml
=> updating StatefulSet and Deployment API Version

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-service.yaml, stable/artifactory-ha/templates/nginx-service.yaml
added support for headless services
=> added support for headless services

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/NOTES.txt, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/artifactory-service.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/NOTES.txt, stable/artifactory/templates/artifactory-service.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Add support for JMX monitoring with Artifactory
fixes #157 
This enabled basic support for JMX monitoring. We can consider adding support for authentication later
=> Add support for JMX monitoring in Artifactory

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Fix an indentation issue with the replicator system property, causing the replicator not to
=> Fix indentation issue

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Remove unused 'artifactory.releasebundle.feature.enabled'.
=> Remove unused 'artifactory.releasebundle.feature.enabled'

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.10.0

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/requirements.lock, stable/xray/requirements.yaml, stable/xray/values.yaml
Allow override of busybox in rabbitmq-ha
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #331 
I diffed to outcome using the `test-values.yaml` and i think there is no relevant change in the generated k8s objects.
Therefore it will support the two requirements asked in the issue.
=> Allow override of busybox in rabbitmq-ha

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.8.2

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.8.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-binarystore.yaml
=> Support 'artifactory.persistence.cacheProviderDir' for on-premise cluster

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ci/nginx-values.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
Fix the format of the template when using `loggers` sidecars so it will include the image tag.
=> [artifactory] Fix missing image tag for logger sidecars

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ci/nginx-values.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml
Fix the format of the template when using loggers sidecars so it will include the image tag.
=> [artifactory-ha] Fix missing image tag for logger sidecars

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/ci/test-values.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
Fix missing image tags for loggers image sidecars.
=> [distribution] Fix missing image tag for logger sidecars

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/ci/test-values.yaml, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/values.yaml
=> Fix JFMC missing logger image tag

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/values.yaml
=> Fix Xray missing logger image tag

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Artifactory 6.10.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> [artifactory-ha] Artifactory 6.10.1

Makefile, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml
This PR updates the stateful set kubernetes api to support the latest release
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #347 
=> Update statefulset kind api and add serviceName spec

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
Updates the xray chart to deploy Xray 2.8.6
=> [stable/xray] Update xray to 2.8.6

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Artifactory 6.10.2

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> [artifactory-ha] Artifactory 6.10.2

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-statefulset.yaml
Update Mission Control version to 3.5.3
Fix update strategy key
=> Mission control 3.5.3

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/README.md, stable/kubexray/templates/deployment.yaml, stable/kubexray/values.yaml
Summoning @rimusz, @jainishshah17 and/or @eldada per the PR template. Thanks for taking the time to review this, it's much appreciated!
Leverage a PriorityClass to ensure your pods survive resource shortages
ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
I ran `make lint` and it passed
I installed this change on an EKS cluster and the priority class appeared as expected.
Adding `priorityClassName` support for k8s-spot-rescheduler.
=> [stable/kubexray] adding priority class support 🔺

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-binarystore.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-binarystore.yaml, stable/artifactory/values.yaml
No variables have been changed, only constant values in templates
=> Update Google Cloud Storage API URL

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/test-values-persistence.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/values.yaml
=> [xray] update Xray to v2.8.7 and add persistence for server and indexer

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-installer-info.yaml
Artifactory 6.10.3.
Update installer-info template.
=> Artifactory 6.10.3. Update installer-info template

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-installer-info.yaml
Artifactory 6.10.3.
Update installer-info template.
=> Artifactory HA 6.10.3. Update installer-info template

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] Update readme with Postgres external db example

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/external-postgres-secret.yaml, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/templates/xray-setup-conf.yaml, stable/xray/values.yaml
=> [xray] Optional support for Postgres with TLS

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/ingress.yaml, stable/artifactory/values.yaml
Add the option to provide additional ingress rules
fixes #365
=> [artifactory] Add the option to provide additional ingress rules

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory-ha/values.yaml
Add the option to provide ingress additional rules for artifactory-ha
fixes #365
=> [artifactory-ha] Add the option to provide additional ingress rules

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Artifactory 6.10.4

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> [artifactory-ha] Artifactory 6.10.4

Makefile, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-server-svc.yaml, stable/xray/values.yaml, test/lint-charts.sh
=> improve kubeval procecess, fix xray server service

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values-large.yaml, stable/artifactory-ha/values-medium.yaml, stable/artifactory-ha/values-small.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values-large.yaml, stable/artifactory/values-medium.yaml, stable/artifactory/values-small.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/values-large.yaml, stable/distribution/values-medium.yaml, stable/distribution/values-small.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/values-large.yaml, stable/mission-control/values-medium.yaml, stable/mission-control/values-small.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/values-large.yaml, stable/xray/values-medium.yaml, stable/xray/values-small.yaml
Add values files for small, medium and large installations
fixes #9
=> Add values files for small, medium and large installations

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> [distribution] Update chart maintainers

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
=> [mission-control] Update chart maintainers

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/templates/deployment.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [xray] Update chart maintainers

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/nginx-artifactory-conf.yaml
Change Artifactory Nginx config to reference the Artifactory service port
=> [artifactory-ha] Change nginx reference to the artifactory service port

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/nginx-artifactory-conf.yaml
Fix Artifactory Nginx config to reference the Artifactory service port
=> [artifactory] Change nginx reference to the artifactory service port

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Update chart maintainers

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> [artifactory-ha] Update chart maintainers

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Update Xray version to 2.8.8

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, test/common.sh, test/e2e-docker4mac.sh, test/e2e-gke.sh, test/e2e-kind.sh, test/e2e-local-gke.sh, test/lint-charts.sh, test/lint-scripts.sh
Remove some more duplicate code from the shell scripts
=> Remove dups

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> Distribution 1.6.1

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Artifactory version to 6.11.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory-ha] Artifactory 6.11.1

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml
Update statfulset apiVersion to apps/v1
=> Update statfulset apiVersion to apps/v1

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.8.9

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
Updated README with persistence enabled for server and indexer.
=> Updated README with persistence enabled for server and indexer

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/ingress.yaml, stable/xray/values.yaml
Add the option to provide additional ingress rules
=> [xray] Add the option to provide additional ingress rules

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Artifactory version 6.11.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> [artifactory-ha] Artifactory version 6.11.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md
=> Update README about how to apply licenses for artifactory HA

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml
Now that nginx config is managed in `values.yaml`, we can simplify init setup of the nginx pod.
=> [artifactory-ha] Simplify nginx setup

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
Now that nginx config is managed in `values.yaml`, we can simplify init setup of the nginx pod.
=> [artifactory] Simplify nginx setup

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/access-bootstrap-creds.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
* Do not mount `access/etc/bootstrap.creds` unless user specifies a custom password or secret (Access already generates a random password if not provided one)
* If custom `bootstrap.creds` is provided (using keys or custom secret), prepare it with an init container so the temp file does not persist
=> [artifactory-ha] Improve handling of Access bootstrap.creds

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
Fix the example for routing traffic to artifactory from the same ingress
fixes #433 
=> [xray] Fix the ingress routing example

.travis.yml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/ingress.yaml
Fix Ingress routing and add an example for routing Xray traffic from the same ingress
fixes #433 
#441 
=> [artifactory-ha] Fix Ingress routing and add an example for routing ingress traffic

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-master-key.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/values.yaml
Adds the option to provide a precreated secret for the master key instead of providing secret through --set or values directly.
=> [xray]: Add the option to provide a precreated secret for master key

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/OWNERS
=> [artifactory] Artifactory 6.11.6

stable/helm-hub-sync/.helmignore, stable/helm-hub-sync/CHANGELOG.md, stable/helm-hub-sync/Chart.yaml, stable/helm-hub-sync/LICENSE, stable/helm-hub-sync/OWNERS, stable/helm-hub-sync/README.md, stable/helm-hub-sync/templates/NOTES.txt, stable/helm-hub-sync/templates/_helpers.tpl, stable/helm-hub-sync/templates/config.yaml, stable/helm-hub-sync/templates/deployment.yaml, stable/helm-hub-sync/templates/secret.yaml, stable/helm-hub-sync/templates/service-account.yaml, stable/helm-hub-sync/values.yaml
=> Add helm-hub-sync chart

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> Distribution version 1.7.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml
Fix existingSharedClaim permissions issue and example
=> Fix existingSharedClaim permissions issue and example

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> [artifactory-ha] Artifactory version 6.12.0

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Artifactory version 6.12.0

.travis.yml, Makefile, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
Enable the Artifactory container's liveness and readiness probes
=> [artifactory] Enable the Artifactory container's liveness and readiness probes

.travis.yml, stable/helm-hub-sync/CHANGELOG.md, stable/helm-hub-sync/Chart.yaml, stable/helm-hub-sync/README.md
=> helm-hub-sync add diagram to readme

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.9.0

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
Fix the nginx server_name directive used with ingress.hosts
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #455 
=> [artifactory] Fix the nginx server_name directive used with ingress.hosts

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml
Fix nginx ingress hostname artifactory ha
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #455 
=> [artifactory-ha] Fix nginx ingress hostname artifactory ha

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/replicator-configmap.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/replicator-configmap.yaml
=> Artifactory version 6.12.1

stable/helm-hub-sync/CHANGELOG.md, stable/helm-hub-sync/Chart.yaml, stable/helm-hub-sync/README.md, stable/helm-hub-sync/templates/NOTES.txt, stable/helm-hub-sync/templates/config.yaml, stable/helm-hub-sync/templates/deployment.yaml, stable/helm-hub-sync/values.yaml
Change 'artifactory.host' to 'artifactory.url'.
=> Change 'artifactory.host' to 'artifactory.url'.

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> artifactory/artifactory-ha version bump to 6.12.2

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
Mission-Control version to 3.5.4
=> Mission-Control version to 3.5.4

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/nginx-service.yaml, stable/artifactory-ha/values.yaml
**What this PR does / why we need it**:  To have the chance to define custom labels for the nginx service
**Which issue this PR fixes**: fixes #474
@amithins
@danielezer 
@eldada 
@rimusz
=> [artifactory-ha] Add custom labels in Nginx service

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Adds the key `waitForDatabase` as an option to skip waiting for DB
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #479 
=> Init container 'wait-for-db' optional with 'waitForDatabase=true/false'

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> Distribution version 1.7.1

.travis.yml, Makefile, stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml
=> Update Kubexray to 0.4.0, other tools updates

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.10.0

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> Distribution version 1.7.2

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] Artifactory 6.13.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> [artifactory-ha] Artifactory 6.13.0

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.10.1

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
Artifactory 6.13.1
Address #496
=> [artifactory] Artifactory 6.13.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
Artifactory 6.13.1
Address #496
=> [artifactory-ha] Artifactory 6.13.1

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> Distribution version 1.7.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Change the preStartCommand to support templating
=> Change preStartCommand to support templating

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.10.4

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.10.5

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/requirements.lock, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.14.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
add support for the `aws-s3-v3` filestore template in order to allow users to attach IAM roles at the pod level instead of attaching the role to the machine the pod is running on. This makes the setup much more secure because instead of having to grant S3 access to every machine in your cluster, you can now just provide access to a specific pod.
fixes #485
=> add support for the aws-s3-v3 filestore template

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.10.7

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/artifactory-service.yaml, stable/artifactory-ha/templates/nginx-service.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-service.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
For cases where user wants to whitelist IPs on the artifactory service (when it's set to `type=LoadBalancer`)
=> Artifactory service whitelist

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ci/ingress-values.yaml, stable/artifactory-ha/ci/nginx-values.yaml, stable/artifactory-ha/requirements.lock, stable/artifactory-ha/requirements.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ci/ingress-values.yaml, stable/artifactory/ci/nginx-values.yaml, stable/artifactory/requirements.lock, stable/artifactory/requirements.yaml, stable/artifactory/values.yaml
1. Update PostgreSQL chart version to 7.0.1
2. Use formal PostgreSQL configuration format
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #529
=> PostgreSQL chart version to 7.0.1. Formal PostgreSQL configuration format

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
https://stackoverflow.com/a/55113540/304690
=> Details on masterKey

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
=> Mission Control 3.5.5

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md
Improve `artifactory.masterKey` description
=> Improve description for `artifactory.masterKey`

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.14.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md
=> Fix README.md format (broken table)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-serviceaccount.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-serviceaccount.yaml, stable/artifactory/values.yaml
Add the option to provide service account annotations to support stuff like the AWS service account IAM role integration - https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
=> Add the option to provide service account annotations

stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/LICENSE, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/templates/NOTES.txt, stable/artifactory-jcr/values.yaml
Initial commit of the Artifactory JCR helm chart
=> Initial commit of the Artifactory JCR helm chart

stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml
Add the appVersion key to JCR chart
=> Add the appVersion key to JCR chart

stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/values.yaml, test/ct.yaml, test/lint-charts.sh
=> Fix JCR chart logo url

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/LICENSE, stable/artifactory-cpp-ce/OWNERS, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-cpp-ce/templates/NOTES.txt, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/LICENSE, stable/artifactory-oss/OWNERS, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/artifactory-oss/templates/NOTES.txt, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/README.md
=> Artifactory: add OSS and C++ CE charts

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/values.yaml
Add an explicit `XRAY_K8S_ENV=true` to let it know it's running in k8s and allow probes without authentication.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #553
=> Prevent probes failing on 403 (Forbidden)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml
Move the added env vars to the right container.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #553
=> Prevent probes failing on 403 (Forbidden) - fixes

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Add support for Artifactory using existing PriorityClass
=> Add support for Artifactory using existing PriorityClass

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 8.2.6
=> Update dependency Artifactory chart version to 8.2.6

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.16.0

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.11.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/templates/nginx-service.yaml, stable/artifactory-ha/values.yaml
There is a kubernetes bug: https://github.com/kubernetes/kubernetes/issues/83070 which screws up the listeners on the ELB. We manually overroad the nginx service values to disable the http listener. This PR brings our manual change into compliance with your chart.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #526 
@amithins @danielezer @eldada @rimusz
=> add toggles for http/https nginx service

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/replicator-configmap.yaml, stable/artifactory-ha/values.yaml
Add missing change to nginx config as part of https://github.com/jfrog/charts/pull/583
=> Fix to the change adding the http(s) toggles in nginx

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/templates/nginx-service.yaml, stable/artifactory/templates/replicator-configmap.yaml, stable/artifactory/values.yaml
Add support for http/https toggling in Nginx config.
=> Adding http(s) toggles in nginx

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 8.3.1
=> Update dependency Artifactory chart version to 8.3.1

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/values.yaml
This PR does two things:
* Add the ability to add annotations to all stateful sets in xray.
* Add the ability to mount custom volumes to all stateful sets in xray.
The fixes in values.yaml should be applied to all charts, it'll remove a warning in annotations.
The fixes to how annotations are parsed should be applied elseware as well.
=> Add dynamic volume and dynamic annotations

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
Mark empty map values with '{}' (Artifactory and Xray charts)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #594 
=> Mark empty map values with '{}'

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 8.3.3
=> Update dependency Artifactory chart version to 8.3.3

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/nginx-deployment.yaml
Changes the nginx pod probes to probe on port 443 when http is disabled.
Came accross this when trying to spin up a completely new install with http disabled. For some reason if the artifactory-ha is created with http enable, and then disabled after, it doesn't break, but this is only the cause when the complete artifactory-ha is stood up with http disabled.
@amithins 
@eldada 
@danielezer 
@rimusz
=> fix: make the probes switch to https if http is disabled

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 8.3.5
=> Update dependency Artifactory chart version to 8.3.5

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.11.3

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> Distribution 1.8.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
Added example for external nginx-ingress; howto forward X-Forwarded-* headers
=> Updated README with nginx-ingress example

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.17.0

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
=> Mission Control 3.5.6

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/replicator-configmap.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/replicator-configmap.yaml
Add new port config support in nginx replicator configmap.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #614 
=> Fix replicator port resolution in nginx replicator configmap

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 8.4.1 (Artifactory 6.17.0)
=> Update dependency Artifactory chart version to 8.4.1 (Artifactory 6.17.0)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-pdb.yaml, stable/artifactory-ha/templates/nginx-pdb.yaml, stable/artifactory-ha/values.yaml
- [-] Variables and other changes are documented in the README.md
Unsure if this should be in the ReadMe or not, I can't see anything about pod disruption budgets in there at the moment
This PR was required for being able to specifically target just the Member and Primary Artifactory pods with a pod disruption budget - otherwise the Nginx pods are included. 
This PR adds another template for specifically targeting the Nginx pods.
Both of these charts target the specific pods by using the component label (which is nginx for Nginx and artifactory-ha for the Primary and Member nodes)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
=> Refined Pod Disruption Budgets (Separated for Nginx and Artifactory pods)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Improve `database.user` and `database.password` logic in order to support more use cases like combining `database.user` and `database.secrets.password` or the other way around.
=> Improve `database.user` and `database.password` logic

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml
Add support for primary or member node specific preStartCommand
fixes #515 
=> Add support for primary or member node specific preStartCommand

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 8.4.4
=> Update dependency Artifactory chart version to 8.4.4

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-statefulset.yaml
Fix JFMC init containers resources
=> Fix JFMC init containers resources

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml
Add support for templating in the `postStartCommand`
=> Add support for templating in the `postStartCommand`

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
=> Fix HA custom DB password indention

stable/artifactory-ha/CHANGELOG.md, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-statefulset.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-indexer-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/values.yaml
Add support for `preStartCommand` and `customVolumeMounts`
fixes #637 
=> Add support for `preStartCommand` and `customVolumeMounts`

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray 2.11.4

stable/kubexray/CHANGELOG.md, stable/kubexray/Chart.yaml, stable/kubexray/README.md
=> kubexray - Add Deprecation Notice

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 6.18.0

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 8.5.0 (Artifactory 6.18.0)
=> Update dependency Artifactory chart version to 8.5.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/UPGRADE_NOTES.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/UPGRADE_NOTES.md
Artifactory & Artifactory-HA Upgrade Docs fix
=> Upgrade Docs fix

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
Fix README.md rendering issue in helm hub
=> Fix readme table rendering

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> Xray pvc fix

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-migration-scripts.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-migration-scripts.yaml
- [x ] Chart Version bumped
- [ x] Variables and other changes are documented in the README.md
Add Unsupported message from 6.18 to 7.2.x (migration)
Note:
To upgrade to Artifactory 7.x from version 6.18, you will need to upgrade to Artifactory 7.3.1 that will be available in the upcoming days, or to a higher version.
https://www.jfrog.com/confluence/display/RTF6X/Release+Notes#ReleaseNotes-Artifactory6.18
=> Add Unsupported  message from 6.18 to 7.2.x (migration)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-serviceaccount.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-serviceaccount.yaml
Fix rendering of Service Account annotations. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #680 
=> Fix rendering of Service Account annotations

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml
* update changelog
Prevents possible websocket issue
=> * bump version of pipelines and chart

README.md, stable/pipelines/Chart.yaml
=> Updated Readme.md

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
=> Increased Nginx proxy_buffers size

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml
- [ x ] CHANGELOG.md updated
- [ x] Variables and other changes are documented in the README.md
=> Add support for NFS directories

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> Artifactory 6.18.1 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Bump Artifactory version

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-installer-info.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-installer-info.yaml, stable/artifactory/values.yaml
Moved installer info to values.yaml so it is fully customizable
=> Moved installer info to values.yaml so it is fully customizable

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Fix javaopts newline issue - use `>-` for this fix
More info please  Look at https://yaml-multiline.info/
This will remove all newlines (including the end) and flatten to a single string.
=> * Fix javaOpts (newline) issue

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> Update Artifactory dependency version

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-hpa.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
=> Pipelines chart v1.0.33

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/pipelines-statefulset.yaml
=> Fix filebeat compute resources, update docs urls

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/nginx-pdb.yaml
Don't deploy nginx PodDisruptionBudget if `nginx.enabled=false`
=> Do not deploy nginx PodDisruptionBudget if nginx.enabled=false

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.1.4 (Artifactory 7.3.2)
=> Update dependency Artifactory chart version to 9.1.4 (Artifactory 7.3.2)

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Artifactory volumeClaimTemplate error on fresh installation (and migration) when artifactory.persistence.existingClaim is used
=> Fix volumeClaimTemplate issue

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
*Update dependency Artifactory chart version to 9.1.5 (Artifactory 7.3.2)
=> Update dependency Artifactory chart version to 9.1.5 (Artifactory 7.3.2)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-secrets.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
Add support for masterKey as secret
=> Add support for masterKey as secret

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.2.1 (Artifactory 7.3.2)
=> Update dependency Artifactory chart version to 9.2.1 (Artifactory 7.3.2)

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/values.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/values.yaml
=> ReadMe fixes

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
* Allow sending error logs to stdout
* Set log level
Although there already are options to configure logging with persistent volume many solutions, especially for Kubernetes, make use of stdout/stderr when gathering logs.
Also, following the best practices of cloud software development there should be such option without a need of changing nginx config directly.
Empty `kubectl logs <pod>` might increase ones heart rate :)
Ref: http://nginx.org/en/docs/ngx_core_module.html#error_log
**Special notes for your …
=> Add nginx log options

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> Inbound from forks - nginx logs

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
=> artifactory-ha: Restore `artifactory-license` volume for the primary node

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> Xray 3.2.3

.gitignore, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, test/common.sh
=> Remove license secret duplication

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-ha/requirements.lock, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.2.3 (Artifactory 7.3.2)
=> Update dependency Artifactory chart version to 9.2.3 (Artifactory 7.3.2)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Fix Artifactory command so SIGTERM will reach java process properly.
=> Fix Artifactory command so SIGTERM will reach java process

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml
Added cache-layer in chain definition of Google Cloud Storage template
=> Added cache-layer in chain definition of Google Cloud Storage template

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml
This makes the template render the script to copy the join key when it is provided by an external secret. Currently this whole block is ignored if `artifactory.joinKey` is not set to any value, so the value in the secret is never applied.
It also applies a couple of the changes from #731 to the node statefulset (I didn't realise the node had it at the time)
=> [artifactory-ha] External joinKey secret + node statefulset resources

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
[artifactory-ha] External joinKey secret + node statefulset resources 
=> [artifactory-ha] External joinKey secret + node statefulset resources 

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml
Support masterKey and joinKey as secrets
=> [ artifactory-ha ] - Support masterKey and joinKey as secrets

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
=> [ artifactory ] - Support masterKey and joinKey as secrets

stable/xray/ci/test-values.yaml
=> CI fix for Xray upgrades

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
Support masterKey and joinKey as secrets
=> [ xray ] - Support masterKey and joinKey as secrets

stable/distribution/ci/test-values.yaml
CI fix for distribution upgrades
=> CI fix for distribution upgrades

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/ci/test-values.yaml, stable/distribution/templates/distribution-secrets.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
Support masterKey and joinKey as secrets
=> [ distribution ] - Support masterKey and joinKey as secrets

stable/mission-control/ci/test-values.yaml
=> CI fix for MC upgrades

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> distribution - 1.8.1

stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/values.yaml
=> Fix cache size

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.2.8 (Artifactory 7.3.2)
=> Update dependency Artifactory chart version to 9.2.8 (Artifactory 7.3.2)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
Added recommended annotation to avoid 413 error
=> Added recommended annotation to avoid 413 error

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-database-secrets.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [ xray ] - Support DB secrets

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/requirements.lock, stable/pipelines/requirements.yaml, stable/pipelines/templates/node-statefulset.yaml, stable/pipelines/values.yaml, test/ct.yaml
=> Pipelines 1.0.36

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/requirements.lock, stable/artifactory/requirements.yaml, stable/artifactory/values.yaml
=> [ artifactory ] - Use dependency charts from https://charts.bitnami.com/bitnami

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/requirements.lock, stable/artifactory-ha/requirements.yaml, stable/artifactory-ha/values.yaml
=> [ artifactory-ha ] - Use dependency charts from https://charts.bitnami.com/bitnami

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/requirements.lock, stable/mission-control/requirements.yaml, stable/mission-control/values.yaml
=> [ mission-control ] - Use dependency charts from https://charts.bitnami.com/bitnami

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/requirements.lock, stable/distribution/requirements.yaml, stable/distribution/values.yaml
=> [ distribution ] - Use dependency charts from https://charts.bitnami.com/bitnami

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/requirements.lock, stable/xray/requirements.yaml
=> [ xray ] - Use dependency charts from https://charts.bitnami.com/bitnami

pipelines/fork_pr.yml, pipelines/pr.yml, pipelines/resources.yml, test/e2e-gke.sh, test/lint-charts.sh
=> Add Pipelines integration

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/artifactory-oss/values.yaml
=> Update dependency Artifactory chart version to 9.3.1 (Artifactory 7.3.2)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> helm v3 command updates for xray

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md
=> helm v3 command changes for mission-control

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/requirements.lock, stable/xray/requirements.yaml, stable/xray/values.yaml
=> Bump dependency charts of rabbitmq and rabbitmq-ha

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md
=> helm v3 commands for distribution

test/cleaner/install_jamadar.sh, test/cleaner/jamadar/templates/deployment.yaml, test/cleaner/override-values.yaml
=> Update jamadar chart

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [ artifactory ] - 7.4.1 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.4.0 (Artifactory 7.4.1)
=> [ artifactory-jcr/oss/cpp ] - Update dependency Artifactory chart version to 9.4.0 (Artifactory 7.4.1)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, test/ct.yaml
=> [ artifactory-ha ] - 7.4.1 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
[ artifactory ] - 6.19.0 release
=> [ artifactory ] - 6.19.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/artifactory-oss/values.yaml
[ artifactory- jcr/oss/cpp ] Update dependency Artifactory chart version to 8.6.0 (Artifactory 6.19.0)
=> [ artifactory- jcr/oss/cpp ] Update dependency Artifactory chart version to 8.6.0 (Artifactory 6.19.0)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml
customInitContainer identation template fix
=> [ xray ] - customInitContainer identation template fix 

Makefile, pipelines/ci-rt.yml, pipelines/fork_pr.yml, test/cleaner/install_jamadar.sh, test/common.sh, test/e2e-rt.sh
=> Improve pipelines for unified

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml
[ artifactory-ha ] - Fix broken support for gcpServiceAccount for googleStorage
=> [ artifactory-ha ] - Fix broken support for gcpServiceAccount for googleStorage

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> Pipelines chart v1.1.1

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [Xray] - Add support to rabbitmq/rabbbitmq-ha existingsecrets

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/templates/_helpers.tpl, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/templates/mission-control-svc.yaml, stable/mission-control/values.yaml
**What this PR does / why we need it**: Upgrade Elasticsearch and Mission Control to 7.6.1 and 4.3.2
=> INST-766 - Upgrade Elasticsearch and Mission Control to 7.6.1 and 4.3.2

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-statefulset.yaml
- [N/A] Variables and other changes are documented in the README.md
While creating umbrella unified charts, we found that we need to make minor modifications to base charts to avoid naming collisions. In this particular fix, we are avoid DB password collision fix. In other words, both xray and RT have same key for DB password, so they were overwriting each other's value.
=> Adding tpl to xray-statefulset for JF_SHARED_PASSWORD

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/buildplane-config-aws.yaml, stable/pipelines/values.yaml
* Upgrades the PIpelines v1.4.6
* Removes the subnetId fields and Nat fields which are not supported in release 1.4.6+
=> Upgrade to Pipelines v1.4.6 

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml
=> Pipelines v1.1.3

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/templates/database-secrets.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
* Add support to db existing secrets
* Fix broken support if `postgresql.postgresqlPassword` not explicitly set
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #834
=> [distribution] - Add support to db existing secrets

pipelines/fork_pr.yml, pipelines/resources.yml
- Use jfrog rt to upload log files to artifactory
- Add link to anonymous logs repo to the user
=> INST-810 - Upload logs to artifactory, provide link in build status

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
It should be false when `useInstanceCredentials` is set to false.
It fixes `useInstanceCredentials` configuration.
No issues filed
=> [artifactory-ha] fix useInstanceCredentials

.travis.yml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
* Fix `artifactory.persistence.awsS3V3.useInstanceCredentials` incorrect conditional logic
* Bump postgresql tag version to `9.6.17-debian-10-r72` in values.yaml
* Bump kubeval version
=> [ artifactory/artifactory-ha ] Fix useInstanceCredentials 

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
Custom initContainer order before migration init container
=> artifactory-ha - Change customInitContiner order

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> Artifactory 7.4.3 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml
=> Artifactory-ha 7.4.3 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
- [x ] Chart Version bumped
- [x ] CHANGELOG.md updated
Xray 3.3.0 release
=> Xray 3.3.0 release

Makefile, README.md, stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.4.4 (Artifactory 7.4.3)
=> [ artifactory-oss/jcr/cpp ] -  Update dependency Artifactory chart version to 9.4.4 (Artifactory 7.4.3)

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/values-ingress-passwords.yaml
=> Pipelines v1.1.4

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
Fix `installerInfo` string format
=> [ artifactory ] - Fix `installerInfo` string format

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/artifactory-oss/values.yaml
…
[ artifactory-oss/jcr/cpp ] -  Update dependency Artifactory chart version to 9.4.5 (Artifactory 7.4.3)
=> [ artifactory-oss/jcr/cpp ] -  Update dependency Artifactory chart version to 9.4.5 (Artifactory 7.4.3)

README.md, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ci/ingress-values.yaml, stable/artifactory-ha/ci/nginx-values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ci/ingress-values.yaml, stable/artifactory/ci/nginx-values.yaml
=> [ artifactory] 6.19.1 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[ artifactory-oss/jcr/cpp ] - Update dependency Artifactory chart version to 8.6.1 (Artifactory 6.19.1)
=> [ artifactory-oss/jcr/cpp ] - Update dependency Artifactory chart version to 8.6.1 (Artifactory 6.19.1)

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/vault-statefulset.yaml
=> [ Don't Merge ] - Pipelines v1.4.7

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/values.yaml
=> [ mission-control ] - Missioncontrol 4.4.0 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
This allows us to configure the amount of metadata database connections. 
Currently Access and Artifactory maxOpenConnections can be defined but not metadata. 
=> [ artifactory ]  Added metadata maxOpenConnections

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [ artifactory-jcr/oss/cpp ] - Update dependency Artifactory chart version to 9.4.6 (Artifactory 7.4.3)

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/templates/mission-control-statefulset.yaml
Fix image version in statefulset
=> [ mission-control ] - Fix image version in statefulset

.github/PULL_REQUEST_TEMPLATE.md
Add chart name as title to PR template
=> Preunified charts - Add chart name as title to PR

.github/PULL_REQUEST_TEMPLATE.md
Add title of the PR with chart name (e.g. `[artifactory]`)
=> Unified charts - Add title of the PR with chart name in PR template

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/ci/test-values.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/ci/test-values.yaml, stable/artifactory/values.yaml
[artifactory] Fixed postgresql README `image` Parameters
=> [artifactory] Fixed postgresql README `image` Parameters

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
Adding Tomcat maxThreads and acceptCounts so that we can tune it for heavy loads.
https://jfrog.com/knowledge-base/how-do-i-tune-artifactory-for-heavy-loads/
https://github.com/jfrog/charts/issues/898
Sorry I don't know how to add the extraConfig part properly to the values.yaml - please help :(
=> [artifactory] Added tomcat acceptCount and maxThreads

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 9.4.9 (Artifactory 7.4.3)
=> [artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 9.4.9 (Artifactory 7.4.3)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [ xray] 2.12.1 release

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/ci/test-values.yaml, stable/mission-control/values.yaml
=> [mission-control] Added Postgres Readme fixes

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
[artifactory] Artifactory-6.20.0 release
=> [artifactory] Artifactory-6.20.0 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml
* Distribution 2.3.0 release
* Update Alpine, Postgresql, Redis and Router versions
=> [distribution]  2.3.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 8.7.0 (Artifactory 6.20.0)
=> [artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 8.7.0 (Artifactory 6.20.0)

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
[artifactory] 7.5.5 release
* Updated Artifactory version to 7.5.5 - https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.5
* Fixes bootstrap configMap permission issue
* Update postgresql tag version to `9.6.18-debian-10-r7`
=> [artifactory] 7.5.5 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 9.5.0 (Artifactory 7.5.5)
=> [artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 9.5.0 (Artifactory 7.5.5)

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/templates/distribution-statefulset.yaml
=> [Distribution] Fixes broken upgrade of charts

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-statefulset.yaml
* Update Mission Control version to 4.4.1
* Fixes Broken upgrades of charts - use `kubectl delete statefulsets <old_statefulset_mission-control>` and run helm upgrade
=> [ mission-control ] 4.4.1 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/values.yaml
**What this PR does / why we need it**: Pipelines v1.5.1 
=> [Pipelines] v1.5.1

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/values.yaml
=> [mission-control] 4.x Upgrade Notes

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-pdb.yaml
[artifactory-ha] Fixes broken PDB issue while upgrading from 6.x to 7.x
Fixes #828 
=> [artifactory-ha] Fixes broken PDB issue while upgrading from 6.x to 7.x

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [Artifactory] Readme update - oracle db configuration

pipelines/ci-rt.yml, pipelines/pr.yml
Helm v2.16.8 is a security release, patching a high-severity security vulnerability found in Go's crypto package affecting all versions of Helm 2 prior to 2.16.8.
More Info :
https://github.com/helm/helm/releases/tag/v2.16.8
=> Bump helm version

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] 7.5.7 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 9.5.2 (Artifactory 7.5.7)
=> [artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 9.5.2 (Artifactory 7.5.7)

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md
=> [Distribution] Added Upgrade notes in readme for 2x upgrades

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/elasticsearch-scripts.yaml, stable/mission-control/templates/elasticsearch-secrets.yaml, stable/mission-control/templates/jfmc-setup-scripts.yaml, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/values.yaml
[mission-control] Add support secrets for Elastic search
=> [mission-control] Add support secrets for Elastic search

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md
[mission-control] 3.5.9 release
=> [mission-control] 3.5.9 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/NOTES.txt
=> [Artifactory HA] Fixed incorrect info in NOTES.txt

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
[xray] Fix broken customVolumeMounts
- Added customVolumeMounts under `router`
=> [xray] Fix broken customVolumeMounts

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml
[distribution] Added support for javaopts for distrubutor and distribution via systemyaml
=> [distribution] Added support for javaopts for distrubutor and distribution via systemyaml

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
=> [Mission-Control] Release mission-control 4.4.2

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> [Xray] Release xray 2.13.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-custom-secrets.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-custom-secrets.yaml, stable/artifactory/values.yaml
=> [artifactory-ha] Support list of custom secrets

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/UPGRADE_NOTES.md
=> [Mission-Control] Added missing steps in upgrade notes for 1x to 2x chart versions

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
[xray] Adding tpl to customVolumeMounts
=> [xray] Adding tpl to customVolumeMounts

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/ci/test-values.yaml, stable/mission-control/values.yaml
[mission-control] Added support for javaopts  via systemyaml
=> [mission-control] Added support for javaopts  via systemyaml

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/ingress.yaml
[xray] Ingress `apiVersion` fix
=> [xray] Ingress `apiVersion` fix

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
CT tool tests have detected an error in artifactory-ha "invalid: spec.containers[0].volumeMounts[2].name: Not found: "bootstrap-config". 
=> [Artifactory-Ha] Fixes bootstrap configMap issue on member node

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
* Update Xray to version `3.5.2`
* Bump alpine to version `3.12`
=> [xray] 3.5.2 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
Make the readiness and liveness probes configurable
=> [distribution] Make the readiness and liveness probes configurable

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/xray-analysis-statefulset.yaml, stable/xray/templates/xray-persist-statefulset.yaml, stable/xray/templates/xray-server-statefulset.yaml, stable/xray/templates/xray-setup-conf.yaml, stable/xray/values.yaml
* Fix broken rabbitmq support when rabbitmq.enabled=true
* Update rabbitmq-ha tag version to `3.8.5-alpine`
* Update rabbitmq tag version to `3.8.5-debian-10-r14`
* Update alpine version to `3.12`
* Update busybox version to `1.31.1`
=> [xray] Fix broken rabbitmq support when rabbitmq.enabled=true

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/values.yaml
**What this PR does / why we need it**: v1.6.0
=> [Pipelines] v1.6.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-serviceaccount.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-serviceaccount.yaml
Fix usage of service account annotations
=> [artifactory] Fix service account annotations

stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/NOTES.txt
helm status artifactory should include --namespace  {{ .Release.Namespace }}
=> [artifactory] NOTES.txt status of service --namespace

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md
=> [Pipelines] v1.6.1

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/requirements.lock, stable/xray/requirements.yaml, stable/xray/values.yaml
* Update Xray version to 2.14.0 - https://www.jfrog.com/confluence/display/XRAY2X/Release+Notes#ReleaseNotes-Xray2.14.0
=> [xray] 2.14.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/ci/default-values.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/ci/default-values.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/ci/default-values.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory] Update dependency Artifactory chart version to 9.6.0 (Artifactory 7.6.1)
=> [artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 9.6.0 (Artifactory 7.6.1)

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/UPGRADE_NOTES.md, stable/mission-control/files/jfmcDataExport.sh
=> [Mission-Control] Added upgrade notes for upgrading to 3.x/4.x chart versions

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
**What this PR does / why we need it**: Enables extensionSync microService in pipelines for helm installs
=> [Pipelines] chart 1.3.2

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml
bumping app version to 1.6.2
- [ X] Chart Version bumped
- [ X] Title of the PR starts with chart name (e.g. `[artifactory]`)
=> Pipelines bump app version

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/_helpers.tpl, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/ingress.yaml, stable/artifactory/values.yaml
=> [artifactory] Add replication ingress object

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/test-rabbitmq-default-values.yaml, stable/xray/ci/test-rabbitmq-values.yaml, stable/xray/requirements.lock, stable/xray/requirements.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-networkpolicy.yaml, stable/xray/templates/xray-svc.yaml, stable/xray/values.yaml
* Added compatability to support latest 7.x rabbitmq subchart when `rabbitmq.enabled=true`
* Update RabbitMQ chart to v7.4.3
* RabbitMQ 7.x chart is [not compatible](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#to-700) with previous rabbitmq 6.x chart in previous Xray 3.x charts
* Please refer [here](https://github.com/jfrog/charts/blob/pre-unified-platform/stable/xray/README.md#special-upgrade-notes) for upgrade notes
=> [xray] Added compatability to support latest 7.x rabbitmq subchart when `rabbitmq.enabled=true`

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
**What this PR does / why we need it**: Fixes call home url to default it to production
=> [pipelines] fixes call home url to default it to production

stable/helm-hub-sync/CHANGELOG.md, stable/helm-hub-sync/Chart.yaml, stable/helm-hub-sync/README.md
=> [helm-hub-sync] Deprecate chart

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory-oss/jcr/cpp] 7.6.2 release
=> [artifactory-oss/jcr/cpp] 7.6.2 release

stable/kubexray/Chart.yaml
=> kubexray - Remove maintainers 

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
=> [artifactory][artifactory-ha] 7.6.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/ci/default-values.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/ci/default-values.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/ci/default-values.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory-oss/jcr/cpp] Added ChartCenter Helm repository in README
=> [artifactory-oss/jcr/cpp] Added ChartCenter Helm repository in README

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/UPGRADE_NOTES.md, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
=> [Distribution] Fix an issue found in upgrade, when using helm upgrade resue values

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-service-headless.yaml
=> [pipelines] fix #1022

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> [xray] 2.15.0 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/ci/migration-disabled-values.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/ci/migration-disabled-values.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
=> [artifactory][artifactory-ha] Add condition to disable migration init container

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-configmaps.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
* Added support for customSidecarContainers, customVolumes, customInitContainers and configMaps
* Update alpine version to 3.12
=> pipelines] Added support for customSidecarContainers, customVolumes, customInitContainers and configMaps

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> [distribution] 2.4.1 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/_helpers.tpl, stable/artifactory-ha/templates/artifactory-database-secrets.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/artifactory-database-secrets.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
* Modified `scheme`  to `artifactory.scheme`
=> [artifactory][artifactory-ha] tpl external database secrets

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-database-secrets.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
[xray] tpl external database secrets
=> [xray] tpl external database secrets

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
This PR adds the ability to set the maxConnections value for the aws-s3-v3 persistent storage option to something other than the default of 50
=> [artifactory][artifactory-ha] Update aws-s3-v3 persistent storage to include option for maxConnections

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml
=> [distribution] Added tpl support for resolving jfrogUrl

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
[artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 10.0.12 (Artifactory 7.6.3)
=> [artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 10.0.12 (Artifactory 7.6.3)

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/values.yaml
=> [Pipelines]: allow overriding pipelines version with one field in the values.yml

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/artifactory-migration-scripts.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/artifactory-migration-scripts.yaml
[artifactory][artifactory-ha] Added condition to disable the migration scripts.
=> [artifactory][artifactory-ha] Added condition to disable the migration scripts.

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml
**What this PR does / why we need it**: fixes configMaps bug for customSideCar containers
=> [pipelines] fixes configMaps bug for customSideCar containers

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/elasticsearch-secrets.yaml, stable/mission-control/values.yaml
* Fix broken support for External Elasticsearch
* Added tpl support for resolve jfrogUrl
=> [mission-control] Fix broken support for External slasticsearch

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
The README section on SSL termination is incorrect.
=> [artifactory][artifactory-ha] Fix the README section on SSL termination.

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/values.yaml
=> [xray] 2.16.0 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/database-secret.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/vault-configmaps.yaml, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/values.yaml
=> [pipelines] Added support for customVolumes, customVolumeMounts, configMaps and customInitcontainers for Vault

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> pipelines: update cp and bp values in system yaml to match overriden tags

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/vault-statefulset.yaml
=> [pipelines] Fix external PG port

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
To enable direct cloud storage download with AWS S3 V3
=> [artifactory][artifactory-ha] AWS S3V3 enable signed url redirect

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/ci/test-values.yaml, stable/mission-control/templates/_helpers.tpl, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/values-large.yaml, stable/mission-control/values-medium.yaml, stable/mission-control/values-small.yaml, stable/mission-control/values.yaml
=> [Mission-Control] 4.5.0 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory][artifactory-ha] 7.7.3 release

Makefile, pipelines/pr.yml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/buildplane-config-aws.yaml, stable/pipelines/templates/buildplane-config-k8s.yaml, stable/pipelines/templates/buildplane-secret-aws.yaml, stable/pipelines/templates/buildplane-secret-k8s.yaml, stable/pipelines/templates/database-secret.yaml, stable/pipelines/templates/filebeat-config.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml, test/common.sh, test/ct.yaml, test/e2e-docker4mac.sh, test/e2e-gke.sh, test/e2e-local-gke.sh, test/e2e-rt.sh
=> [pipelines] chart 1.4.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
[artifactory][artifactory-ha] 6.21.0 release
=> [artifactory][artifactory-ha] 6.21.0 release

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-svc.yaml, test/ct.yaml
Expose Elasticsearch HTTP port with the mission control service
=> [mission-control] Expose Elasticsearch HTTP port with the mission control service

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [xray] 3.8.0 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/values.yaml, test/ct.yaml
=> [xray] 2.16.1 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
=> [Pipelines] Add support for external rabbitmq and redis

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-role.yaml, stable/pipelines/templates/pipelines-rolebinding.yaml, stable/pipelines/values.yaml
**What this PR does / why we need it**: Pipelines chart version 1.4.2
=> [Pipelines] chart 1.4.2

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/templates/mission-control-custom-secrets.yaml, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/values.yaml
=> [mission-control] Add support for custom secrets

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/vault-configmaps.yaml, stable/pipelines/templates/vault-role.yaml, stable/pipelines/templates/vault-rolebinding.yaml, stable/pipelines/templates/vault-secret.yaml, stable/pipelines/templates/vault-service-headless.yaml, stable/pipelines/templates/vault-service.yaml, stable/pipelines/templates/vault-serviceaccount.yaml, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/values.yaml
=> [pipelines] chart v1.4.3 

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/OWNERS, stable/xray/README.md, stable/xray/values.yaml
=> [xray] 2.16.2 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory][artifactory-ha] 7.7.8 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp] Update dependency Artifactory chart version to 11.0.1 (Artifactory 7.7.8)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] 3.8.5 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [xray] 3.8.6 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/values.yaml
=> [PIPELINES] m lock flag for vault to secure settings and removed external vault from readme until pipelines-1.9.0 supports it.

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/security-mitigation.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/security-mitigation.yaml
=> Adding security mitigation files to artifactory charts

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/security-mitigation.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/security-mitigation.yaml
=> fix broken migitation yaml

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/security-mitigation.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/security-mitigation.yaml
=> Fixing mitigation yaml lint issue

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md
=> [distribution] readme updates

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md
=> [mission-control] Updates to README

stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md
=> [artifactory-jcr] readme updates

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> [xray] 2.16.4 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
In case of external DB, We don't need to wait for DB to come up . When setting "waitForDatabase: false" container startup still waits for DB - This issue is fixed by adding an ENV variable `SKIP_WAIT_FOR_EXTERNAL_DB` set to true 
=> [artifactory][artifactory-ha] Fixed broken issue - when setting `waitForDatabase: false` container startup still waits for DB

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml
This PR resolves the issues with running Pipelines in Openshift with all non-root based docker images. Pipelines installer must still have root privileges so we have to escalate it through a SCC to pass certification for Redhat Openshift.
PTRENG-1120
=> [PIPELINES] PTRENG-1120 Added SCC to run pipelines as non-root docker based images

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/ci/test-values.yaml, stable/mission-control/templates/_helpers.tpl, stable/mission-control/templates/jfmc-setup-scripts.yaml, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/templates/postgresql-setup-script.yaml, stable/mission-control/values.yaml
=> [mission-control] Update filebeat version to 7.9.2

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
=> [artifactory][artifactory-ha] Update filebeat version to 7.9.2

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml
=> [distribution] Update filebeat version to 7.9.2

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [xray] 3.8.7 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/security-mitigation.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/security-mitigation.yaml
=> Setting chart coordinates in migitation yaml

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
Security best practice and required for Openshift / Redhat certification process of Operators. Also required for customers who have rook-cph enabled in their Openshift clusters as root containers will not run.
PTRENG-1120
Required for security certification in Redhat
=> [ARTIFACTORY/ARTIFACTORY-HA] Remove root based init container use CAP_CHOWN instead.

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] 3.8.8 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> [Pipelines] Hardcodes router refresh interval

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-statefulset.yaml
=> [Mission-control] Fix failure when using existing pvc

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
=> [artifactory][artifactory-ha] 7.9.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce]  Update dependency Artifactory chart version to 11.1.0 (Artifactory 7.9.0)

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
**What this PR does / why we need it**: We have made changes to our saas-deployer, where pipelines is configured to use internal artifactory endpoint for router topology. This PR supports router configuration for the same. 
=> [Pipelines] updates pipeline charts to set router configuration

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/values.yaml
=> [pipelines] 1.8.0, added support for resources in init containers

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/mission-control-statefulset.yaml
=> [mission-control] Added support for resources in init containers

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [xray] 3.9.1 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
…ble in values.yaml
- [ X] Title of the PR starts with chart name (e.g. `[artifactory]`)
=> [pipelines] add artifactoryHealthCheckIntervalInMins to system.yaml

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
=> [pipelines] readiness and liveness probe configurations

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/UPGRADE_NOTES.md, stable/xray/templates/xray-statefulset.yaml
=> [xray] Fixed broken joinkey condition logic

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/values.yaml
This PR fixes the charts in Pipelines to use the same mechanism in other charts to have both a customInitContainer and customInitBeginContainer. The placement of customInitBeginContainer as the first container and customInitContainer as the last container. Currently Pipelines chart has only customInitContainer and it is first for vault and last for pipeline's statefulset which causes issues.
PTRENG-1120
Current implementation has customInitContainer in different …
=> [PIPELINES] customInitBeginContainer and customInitContainer fixes

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/OWNERS, stable/pipelines/values.yaml
=> [pipelines] adding configurable healthcheck for router

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] Add global support for customInitContainersBegin

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/templates/_helpers.tpl, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/values.yaml
=> [mission-control] Add support for customInitContainersBegin

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/_helpers.tpl, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
=> [distribution] 2.5.1 release , add support for customInitContainersBegin

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> [xray] 2.16.6 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> [pipelines] Adds postgress healthcheck interval and timeout

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml
=> [Artifactory-HA] Add support to allow more than 1 Primary in Artifactory-ha STS

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-pdb.yaml, stable/artifactory-ha/templates/artifactory-primary-pdb.yaml, stable/artifactory-ha/templates/artifactory-secrets.yaml, stable/artifactory-ha/values.yaml
=> [artifactory-ha] Fix PodDisruptionBudget selector issue

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1164
=> [artifactory][artifactory-ha] Priority class support, fixes #1164

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory][artifactory-ha] 7.10.2 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] Update dependency Artifactory chart version to 11.4.0 (Artifactory 7.10.2)

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
This PR is added to support external vault.
I have read the CLA Document and I hereby sign the CLA
=> [pipelines] external vault adoption

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
=> [artifactory/ artifactory-ha] Added flag to disable prepare-custom-persistent-volume init container

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values-ingress.yaml
=> [pipelines] corrected rabbitMQ properties in values-ingress.yaml

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml
=> [jfrog-platform] Logo path fix

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [xray] 3.10.3 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [xray] Update router version to 1.4.4

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml
=> [distribution] Update router version to 1.4.4

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/values.yaml
=> [mission-control] Update router version to 1.4.4

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/rabbitmq-service-vm-int-lb.yaml
=> [pipelines] Fix rabbitmq service

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md
make upgrade directions a little easier to copy and paste
=> [pipelines] Update README.md

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> [xray] 2.6.10 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory][artifactory-ha] 7.10.5 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
Adds the `enablePathStyleAccess` value to the `awsS3V3` [section](https://github.com/jfrog/charts/blob/870ea8d7f500caae95bcece42574acecd7ee43ac/stable/artifactory-ha/values.yaml#L1021).
fixes #1234
=> [artifactory][artifactory-ha] Add enablePathStyleAccess for aws-s3-v3 persistence type

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] Update dependency Artifactory chart version to 11.4.4 (Artifactory 7.10.5)

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml
=> [jfrog-platform] Update dependency artifactory charts (Artifactory 7.10.5)

Makefile, pipelines/pr.yml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/requirements.lock, stable/xray/requirements.yaml, test/ct.yaml
https://helm.sh/blog/new-location-stable-incubator-charts/
=> [Xray] Change stable repository location to https://charts.helm.sh/stable

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/requirements.lock, stable/pipelines/requirements.yaml, stable/pipelines/values-ingress-external-secret.yaml, test/ct.yaml
=> [Pipelines] Update dependency bitnami chart

Makefile, pipelines/ci-rt.yml, pipelines/pr.yml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml
=> [Jfrog platform ] Updated dependencies for platform chart

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] Update dependency Artifactory chart version to 11.4.5 (Artifactory 7.10.6)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/default-values.yaml, stable/xray/ci/global-section-values.yaml, stable/xray/ci/test-rabbitmq-default-values.yaml, stable/xray/values-large.yaml, stable/xray/values-medium.yaml, stable/xray/values-small.yaml
=> [xray] 3.11.1 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/default-values.yaml, stable/xray/ci/test-rabbitmq-default-values.yaml, stable/xray/requirements.lock, stable/xray/requirements.yaml
=> [xray] - Change stable repository location path

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/templates/xray-system-yaml.yaml, stable/xray/values.yaml
=> [Xray] Release xray 3.11.2

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/templates/distribution-system-yaml.yaml, stable/distribution/values.yaml
* Update Distribution to version `2.5.2` - [Release notes](https://www.jfrog.com/confluence/display/JFROG/Distribution+Release+Notes#DistributionReleaseNotes-Distribution2.5.2)
* Pass system.yaml via external secret for advanced usecases
* Bugfix - stateful set not picking up changes to database secrets
=> [distribution] 2.5.2 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml
=> [pipelines] 1.8.12 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/UPGRADE_NOTES.md, stable/artifactory-ha/templates/artifactory-access-config.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/artifactory-service.yaml, stable/artifactory-ha/templates/artifactory-system-yaml.yaml, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory-ha/templates/nginx-certificate-secret.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/templates/nginx-service.yaml, stable/artifactory-ha/templates/servicemonitor.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/UPGRADE_NOTES.md, stable/artifactory/templates/artifactory-access-config.yaml, stable/artifactory/templates/artifactory-service.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/artifactory-system-yaml.yaml, stable/artifactory/templates/ingress.yaml, stable/artifactory/templates/nginx-certificate-secret.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/templates/nginx-service.yaml, stable/artifactory/templates/servicemonitor.yaml, stable/artifactory/values.yaml
* Updated Artifactory version to 7.11.2 - [Release Notes](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.11)
* Updated port namings on services and pods to allow for istio protocol discovery
* Change semverCompare checks to support hosted Kubernetes
* Add flag to disable creation of ServiceMonitor when enabling prometheus metrics
* Prevent the PostHook command to be executed if the user did not specify a command in the values file
* Fix issue with tls file generation when nginx.https.enabled is false
* Updated Artifactory version to 7.11.2
* Bugfix - access.config.import.xml override Access Federation …
=> [artifactory][artifactory-ha] 7.11.2 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 7.11.2 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml
=> [jfrog-platform]  Update dependency artifactory chart version (Artifactory 7.11.2)

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [Xray] Support actualUsername for Azure and external rabbitmq credentials from secret

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/templates/xray-svc.yaml
This PR updates all the port names to include a protocol prefix. This is important for installations that would like to use istio as it relies on these prefixes to determine the protocol of the port. (See [here](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/))
I have updated every port that I could find that didn't already have a port name that included the protocol.
There's a 15 character limit on port names, so I had to chomp some …
=> [xray] Add protocol to port names in for istio

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [xray] 3.12.0 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] Updated port namings on services and pods to allow for istio protocol discovery

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory][artifactory-ha] 6.23.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] Update dependency Artifactory chart version to 8.10.1 (Artifactory 6.23.3)

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 7.11.5 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/templates/NOTES.txt, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/api-ingress.yaml, stable/pipelines/templates/api-service.yaml, stable/pipelines/templates/pipelines-service-headless.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/pipelines-system-yaml.yaml, stable/pipelines/templates/vault-secret.yaml, stable/pipelines/templates/vault-service-headless.yaml, stable/pipelines/templates/vault-service.yaml, stable/pipelines/templates/vault-statefulset.yaml, stable/pipelines/templates/www-ingress.yaml, stable/pipelines/templates/www-service.yaml, stable/pipelines/values-ingress-external-secret.yaml, stable/pipelines/values-ingress-passwords.yaml, stable/pipelines/values.yaml
* Change semverCompare checks to support hosted Kubernetes
* Updated port namings on services and pods to allow for istio protocol discovery
* Update alpine version to 3.12.1
* Pipelines v1.9.8
* Pipelines v1.9.2
* Fixed external Vault support
* Add support for `pipelines.extraEnvironmentVariables` to pass more environment variables to Pipelines services
* Bugfix - Issue with custom image tags
* Update console output with the correct url for accessing pipelines
* Pipelines v1.9.1
* Adds template microservice
* Added support to provide join-key and master-key from secret
* Add steps for using system.yaml via external secret for advanced usecases
* …
=> [pipelines] 1.9.8 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-role.yaml, stable/pipelines/templates/pipelines-rolebinding.yaml, stable/pipelines/values.yaml
=> [pipelines] Update RBAC rules

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> [Distribution] Updated distribution to 2.5.3

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [Xray] Release xray 3.13.0

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> [xray] 2.6.11 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml
=> [pipelines] Critical fix in configuring templatesync container

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/global-section-values.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-database-secrets.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] 3.14.1 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values-large.yaml, stable/xray/values-medium.yaml, stable/xray/values-small.yaml
=> Release xray 3.14.3

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/ci/global-section-values.yaml, stable/distribution/templates/_helpers.tpl, stable/distribution/values.yaml
=> Release distribution 2.5.4

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
This PR should support group-id instead of using the the same number for uid & gid.  
There is some use cases we need to define different uid's & gid's.
=> Don't Merge [artifactory][artifactory-ha] Add gid support for artifactory statefulset

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [Xray] Release 3.15.1

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml
=> [artifactory] Fix gid support 

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] 6.23.7 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md
=> [xray] 2.16.13 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/templates/additional-resources.yaml, stable/xray/values.yaml
=> [Xray] support for additional resources

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/_helpers.tpl, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/ingress.yaml, stable/artifactory/values.yaml
=> [artifactory/artifactory-ha] Release artifactory 7.12.6

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/ci/global-section-values.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/additional-resources.yaml, stable/pipelines/templates/pipelines-networkpolicy.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
=> [pipelines] Release pipelines 1.10.0

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [Xray] Release xray 3.15.3

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/additional-resources.yaml, stable/distribution/values.yaml
=> [distribution] 2.6.0 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/templates/xray-svc.yaml, stable/xray/values.yaml
=> [Xray] Release xray 3.16.0

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
=> [distribution] support hostAliases , router update

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] Update dependency charts

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 7.12.8 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/_helpers.tpl, stable/jfrog-platform/values.yaml
=> [Jfrog platform] - add support to resolve jfrogUrl

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [xray] 3.17.4 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ci/access-tls-values.yaml, stable/artifactory-ha/ci/global-values.yaml, stable/artifactory-ha/ci/test-values.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ci/access-tls-values.yaml, stable/artifactory/ci/global-values.yaml, stable/artifactory/ci/test-values.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml
=> [artifactory][artifactory-ha] 7.15.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/artifactory-oss/values.yaml
=> [artifactory-oss/jcr/cpp-ce] 7.15.3 artifactory release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [xray] Update router version to `7.15.2`

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/ci/ha-values.yaml, stable/mission-control/values.yaml
=> [distribution][mission-control] update router version to 7.15.2

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> [pipelines] 1.12.2 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml, stable/jfrog-platform/templates/_helpers.tpl, stable/jfrog-platform/values.yaml, stable/xray/values.yaml
=> [jfrog-platform] 7.15.3 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
=> [artifactory] 6.23.13 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/artifactory-oss/values.yaml
=> [artifactory-oss/jcr/cpp-ce] 6.23.13 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> [distribution] 2.6.1 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Xray release 3.18.0

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/nginx-certificate-secret.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/nginx-certificate-secret.yaml
=> [artifactory/artifactory-ha]  7.15.4 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 7.15.4 artifactory release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-role.yaml, stable/pipelines/templates/pipelines-rolebinding.yaml, stable/pipelines/values.yaml
=> [pipelines] update RBAC rules for Pipelines

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
* Removed bintray URL references in the chart
* Update router version to `7.15.3`
=> [xray] 3.18.1 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml
=> [jfrog-platfrom] 7.15.4 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> [Pipelines] Enable livelogs

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml
=> [mission-control] 4.6.5 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml
=> [jfrog-platform] 7.17.4 Release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/requirements.lock, stable/jfrog-platform/requirements.yaml
=> Set default JFrog helm repository charts.jfrog.io

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/values.yaml
=> [artifactory] 7.17.9 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.lock, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/requirements.lock, stable/artifactory-ha/requirements.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/artifactory-serviceaccount.yaml, stable/artifactory-ha/templates/filebeat-configmap.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.lock, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/requirements.lock, stable/artifactory/requirements.yaml, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/artifactory-serviceaccount.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/filebeat-configmap.yaml, stable/artifactory/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.lock, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/requirements.lock, stable/xray/requirements.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [artifactory][artifactory-ha][xray] Helm V3 compatible charts

pipelines/ci-rt.yml, pipelines/pr.yml, stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 7.18.3 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
=> [artifactory] 7.18.6 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml
Signed-off-by: Matteo Maponi <matteo.maponi@gmail.com>
**Which issue this PR fixes**
This is specular to the work done here (https://github.com/jfrog/charts/pull/1194) for the pre-unified branch.
=> [artifactory/artifactory-ha] priorityClassName management for the charts 

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md, stable/artifactory/values.yaml
=> [artifactory] 6.23.19 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/values.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/README.md, stable/mission-control/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/values.yaml
=> [distribution][xray][mission-control]Fetch docker images from  releases-docker.jfrog.io

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/ci/default-values.yaml, stable/mission-control/ci/global-section-values.yaml, stable/mission-control/ci/ha-values.yaml, stable/mission-control/ci/test-values.yaml
=> [mission-control] 4.7.4 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/default-values.yaml, stable/xray/ci/global-section-values.yaml, stable/xray/ci/test-rabbitmq-replicaCount-values.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-hpa.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] 3.25.1 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> [pipelines] 1.15.3 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] 6.23.21 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] 7.19.8 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl
=> [xray] 3.26.1, MC 4.7.5, artifactory-cpp-ce/jcr/oss] 7.19.8 releases

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] 7.19.9 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] 6.23.23 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 6.23.23 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
=> [artifactory] 7.21.2 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.lock, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/ci/default-values.yaml, stable/distribution/ci/global-section-values.yaml, stable/distribution/ci/test-values.yaml, stable/distribution/requirements.lock, stable/distribution/requirements.yaml, stable/distribution/templates/_helpers.tpl, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values-large.yaml, stable/distribution/values-medium.yaml, stable/distribution/values-small.yaml, stable/distribution/values.yaml
=> [distribution] 2.8.1 release

stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.lock, stable/mission-control/Chart.yaml, stable/mission-control/ci/global-section-values.yaml, stable/mission-control/requirements.lock, stable/mission-control/requirements.yaml, stable/mission-control/templates/_helpers.tpl, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/values.yaml
=> [mission-control] 4.7.7 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [xray] 3.27.2 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml
=> [jfrog-platform] 7.21.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml
=> [artifactory] 7.21.3 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/ci/ha-values.yaml, stable/pipelines/ci/hpa-values.yaml, stable/pipelines/values.yaml
=> [pipelines] 1.16.1 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/_helpers.tpl, stable/xray/values.yaml
=> [xray] 3.27.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] 7.21.5 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [Jfrog-platform] 7.21.5 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 7.21.7 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] 7.21.7 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [xray] 3.27.4 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml
=> [distribution] 2.8.2 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] 6.23.25 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 6.23.25 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] 7.21.8 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [artifactory] 7.21.12 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml
=> [jfrog-platform] 7.23.3 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/README.md, stable/pipelines/ci/global-section-values.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/default-values.yaml, stable/xray/ci/global-section-values.yaml, stable/xray/ci/test-rabbitmq-replicaCount-values.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-custom-secrets.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] Updated elasticsearch heap memory limits

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml
=> [pipelines] 1.17.8 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml
=> [jfrog-platform] 7.25.6 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/mission-control/CHANGELOG.md, stable/mission-control/Chart.yaml, stable/mission-control/ci/global-section-values.yaml, stable/mission-control/templates/_helpers.tpl, stable/mission-control/templates/mission-control-statefulset.yaml, stable/mission-control/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml
=> [jfrog-platform] 7.25.7 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.lock, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.lock, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.lock, stable/artifactory-oss/Chart.yaml
=> [artifactory-oss/jcr/cpp-ce] 7.25.7 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] 6.23.28 release

.gitignore, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] 6.23.31 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 6.23.31 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml
=> [artifactory] 7.27.10 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml
=> [pipelines] 1.19.4 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/ci/default-values.yaml, stable/distribution/ci/global-section-values.yaml, stable/distribution/ci/test-values.yaml, stable/distribution/templates/_helpers.tpl, stable/distribution/templates/distribution-custom-secrets.yaml, stable/distribution/templates/distribution-serviceaccount.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml
=> [distribution] 2.10.3 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] 3.37.1 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [jfrog-platform] 10.0.4 release

pipelines/ci-rt.yml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.1.0 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/README.md, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/README.md
=> [artifactory] 6.23.36 release

stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/requirements.lock, stable/artifactory-cpp-ce/requirements.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-jcr/requirements.lock, stable/artifactory-jcr/requirements.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md, stable/artifactory-oss/requirements.lock, stable/artifactory-oss/requirements.yaml
=> [artifactory-oss/jcr/cpp-ce] 6.23.36 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/insight/ci/test-values.yaml, stable/insight/templates/_helpers.tpl, stable/insight/templates/insight-statefulset.yaml, stable/insight/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [artifactory] 7.29.8 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.1.1 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.2.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/README.md, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/README.md, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/README.md
=> [artifactory-oss/jcr/cpp-ce] 7.33.8 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/README.md, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.3.0 release

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/pipelines-hpa.yaml, stable/pipelines/templates/pipelines-service-headless.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.3.1 release

examples/artifactory/binarystore/README.md, examples/artifactory/binarystore/templates/NFS-multiple-mounts.xml, examples/artifactory/binarystore/templates/NFS-single-mount.xml, examples/artifactory/binarystore/templates/azure-blob-storage-cluster.xml, examples/artifactory/binarystore/templates/azure-blob-storage-direct.xml, examples/artifactory/binarystore/templates/cluster-file-system.xml, examples/artifactory/binarystore/templates/cluster-google-storage-provider-chain.xml, examples/artifactory/binarystore/templates/s3-storage-v3-cluster-provider-chain.xml, examples/artifactory/binarystore/templates/s3-storage-v3-direct-identity-credential.xml, examples/artifactory/binarystore/templates/s3-storage-v3-direct-provider-chain.xml
=> [examples] Add new examples for Artifactory binaryStore XML

examples/artifactory/plugins/README.md
=> [examples] Add new examples for adding artifactory plugins using secrets

stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/insight/templates/insight-statefulset.yaml, stable/insight/templates/logger-configmap.yaml, stable/insight/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/logger-configmap.yaml, stable/xray/templates/xray-priority-class.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.4.0 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/ci/default-values.yaml, stable/pipelines/ci/global-section-values.yaml, stable/pipelines/ci/ha-values.yaml, stable/pipelines/ci/hpa-values.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/pipelines-priority-class.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [jfrog-platform] 10.4.1 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-statefulset.yaml
=> [pipelines] 1.22.4 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platorm] 10.5.1 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [artifactory] 7.37.15 release

stable/jfrog-platform/Chart.yaml
=> [jfrog-platform] 10.5.2 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.6.0 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/_helpers.tpl, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.6.1 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/_helpers.tpl, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/insight/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [artifactory] 7.38.8 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [jfrog-platform] 10.6.2 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.lock, stable/pipelines/Chart.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
=> [jfrog-platform] 10.6.3 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/README.md, stable/jfrog-platform/ci/platform-ha-values.yaml, stable/jfrog-platform/templates/NOTES.txt, stable/jfrog-platform/templates/_helpers.tpl, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.7.0 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/NOTES.txt, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-custom-secrets.yaml, stable/xray/templates/xray-database-secrets.yaml, stable/xray/templates/xray-secrets.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/templates/xray-system-yaml.yaml, stable/xray/templates/xray-unified-secret.yaml, stable/xray/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/jfrog/charts/issues/1599
=> [xray] 3.54.5 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml
=> [jfrog-platform] 10.8.2 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/ci/default-values.yaml, stable/pipelines/ci/global-section-values.yaml, stable/pipelines/ci/ha-values.yaml, stable/pipelines/ci/hpa-values.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.8.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pdn-server/CHANGELOG.md, stable/pdn-server/Chart.yaml, stable/pdn-server/ci/default-values.yaml, stable/pdn-server/templates/_helpers.tpl, stable/pdn-server/templates/pdnserver-deployment.yaml, stable/pdn-server/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml
=> [jfrog-platform] 10.8.4 release

Makefile, stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/insight/README.md, stable/insight/ci/test-values.yaml, stable/insight/templates/_helpers.tpl, stable/insight/templates/insight-statefulset.yaml, stable/insight/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.8.5 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/README.md, stable/distribution/ci/test-values.yaml, stable/distribution/templates/_helpers.tpl, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pdn-server/CHANGELOG.md, stable/pdn-server/Chart.yaml, stable/pdn-server/ci/global-section-values.yaml, stable/pdn-server/templates/pdnserver-deployment.yaml, stable/pdn-server/values.yaml
=> [jfrog-platform] 10.8.6 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/pipelines-unified-secret.yaml, stable/pipelines/values.yaml
=> [pipelines] 1.27.5 release

stable/artifactory/CHANGELOG.md, stable/artifactory/templates/artifactory-statefulset.yaml
Fixes a bug in the *artifactory* Helm chart that made it unusable
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1650 
@chukka
=> [artifactory] Fix duplicate volumes for userPluginSecrets

stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl
=> [jfrog-platform] 10.9.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.9.1 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/.helmignore, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.9.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/test-values.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.9.4 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/ci/global-section-values.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/vault-pg-storage-secret.yaml, stable/pipelines/values.yaml
=> [pipelines] 1.28.1 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ci/test-values.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ci/test-values.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/artifactory/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [artifactory] 7.47.10 release

stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/insight/ci/test-values.yaml, stable/insight/templates/_helpers.tpl, stable/insight/templates/insight-statefulset.yaml, stable/insight/values.yaml
=> [insight] 1.13.0 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/ci/default-values.yaml, stable/pipelines/templates/NOTES.txt, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/api-service-internal.yaml, stable/pipelines/templates/api-service.yaml, stable/pipelines/templates/pipelines-cron-statefulset.yaml, stable/pipelines/templates/pipelines-hookhandler-hpa.yaml, stable/pipelines/templates/pipelines-hookhandler-statefulset.yaml, stable/pipelines/templates/pipelines-internalapi-hpa.yaml, stable/pipelines/templates/pipelines-internalapi-statefulset.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/pipelines-steptrigger-statefulset.yaml, stable/pipelines/templates/pipelines-sync-hpa.yaml, stable/pipelines/templates/pipelines-sync-statefulset.yaml, stable/pipelines/templates/pipelines-trigger-hpa.yaml, stable/pipelines/templates/pipelines-trigger-statefulset.yaml, stable/pipelines/templates/www-service.yaml, stable/pipelines/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/ci/test-values.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.11.0 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-pdb.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [xray] 3.67.9 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/ci/default-values.yaml, stable/pipelines/templates/pipelines-cron-statefulset.yaml, stable/pipelines/templates/pipelines-hookhandler-statefulset.yaml, stable/pipelines/templates/pipelines-steptrigger-statefulset.yaml, stable/pipelines/templates/pipelines-sync-statefulset.yaml, stable/pipelines/templates/pipelines-trigger-statefulset.yaml
=> [jfrog-platform] 10.12.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml, stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.12.1 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/vault-pg-storage-secret.yaml, stable/pipelines/values.yaml
**What this PR does / why we need it**: Update pipelines version to 101.38.1
=> Update pipelines version to 101.38.1

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/_helpers.tpl, stable/jfrog-platform/templates/migration-hook.yaml, stable/jfrog-platform/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1750 
=> [jfrog-platform] 10.12.2 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/migration-hook.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/migration-hook.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.12.3 release

examples/artifactory/system-properties/values-system-properties.yaml, examples/jfrog-platform/values/values-artifactory-xray.yaml
**What this PR does / why we need it**: Adding a simple example for the **jfrog-platform** install with artifactory and xray only
=> Add example for jfrog-platform install with artifactory and xray only

stable/pdn-node/CHANGELOG.md, stable/pdn-node/Chart.yaml, stable/pdn-node/templates/servicemonitor.yaml, stable/pdn-node/templates/statefulset.yaml, stable/pdn-node/values.yaml
=> [pdn-node] 1.7.6 release

stable/pdn-server/CHANGELOG.md, stable/pdn-server/Chart.yaml, stable/pdn-server/templates/servicemonitor.yaml, stable/pdn-server/values.yaml
=> [pdn-server] 1.7.6 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/migration-hook.yaml
=> [jfrog-platform] 10.13.0 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/migration-hook.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.13.1 release

stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/pipelines-hookhandler-hpa.yaml, stable/pipelines/templates/pipelines-hpa.yaml, stable/pipelines/templates/pipelines-internalapi-hpa.yaml, stable/pipelines/templates/pipelines-internalapi-statefulset.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/pipelines-sync-hpa.yaml, stable/pipelines/templates/pipelines-trigger-hpa.yaml, stable/pipelines/values.yaml
=> [pipelines] 1.41.3 release

stable/pdn-node/CHANGELOG.md, stable/pdn-node/Chart.yaml, stable/pdn-node/templates/servicemonitor.yaml, stable/pdn-node/templates/statefulset.yaml, stable/pdn-node/templates/svc.yaml, stable/pdn-node/values.yaml
=> [pdn-node] 1.8.4 release

stable/pdn-server/CHANGELOG.md, stable/pdn-server/Chart.yaml, stable/pdn-server/templates/deployment.yaml, stable/pdn-server/templates/servicemonitor.yaml, stable/pdn-server/templates/svc.yaml, stable/pdn-server/values.yaml
=> [pdn-server] 1.8.4 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/migration-hook.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1794 
=> [jfrog-platform] 10.14.2 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1791 
=> [jfrog-platform] 10.14.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.14.4 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.14.7 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/insight/CHANGELOG.md, stable/insight/Chart.yaml, stable/insight/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/migration-hook.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.14.8 release 

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/NOTES.txt, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.15.2 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/files/binarystore.xml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/files/binarystore.xml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1828 
=> [jfrog-platform] 10.16.2 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/distribution/.helmignore, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/ci/newrelic-values.yaml, stable/distribution/ci/test-values.yaml, stable/distribution/templates/distribution-newrelic.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1851 
=> [jfrog-platform] 10.16.4 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/README.md, stable/xray/ci/global-section-values.yaml, stable/xray/templates/_helpers.tpl, stable/xray/templates/xray-ipa-deployment.yaml, stable/xray/templates/xray-ipa-svc.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/templates/xray-svc.yaml, stable/xray/values.yaml
=> [xray] 3.94.5 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/ci/loggers-values.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/artifactory-unified-secret.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/ci/loggers-values.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/artifactory-unified-secret.yaml, stable/artifactory/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1881 , #1882 , #1883 
=> [artifactory] 7.84.11 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/_helpers.tpl, stable/artifactory-ha/templates/nginx-deployment.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/nginx-deployment.yaml, stable/pipelines/CHANGELOG.md, stable/pipelines/Chart.yaml, stable/pipelines/templates/_helpers.tpl, stable/pipelines/templates/pipelines-cron-statefulset.yaml, stable/pipelines/templates/pipelines-hookhandler-statefulset.yaml, stable/pipelines/templates/pipelines-internalapi-statefulset.yaml, stable/pipelines/templates/pipelines-statefulset.yaml, stable/pipelines/templates/pipelines-steptrigger-statefulset.yaml, stable/pipelines/templates/pipelines-sync-statefulset.yaml, stable/pipelines/templates/pipelines-trigger-statefulset.yaml, stable/pipelines/values.yaml
=> [artifactory] 7.84.12 release

stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/ci/loggers-values.yaml, stable/distribution/templates/distribution-statefulset.yaml, stable/distribution/templates/distribution-unified-secret.yaml, stable/distribution/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/templates/_helpers.tpl
=> [jfrog-platform] 10.18.1 release

stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-ipa-deployment.yaml, stable/xray/templates/xray-server-deployment.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> Xray release 3.98.2

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/_helpers.tpl, stable/artifactory-ha/templates/artifactory-license-secret.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/artifactory-license-secret.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [jfrog-platform] 10.18.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.19.2 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 10.19.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.19.4 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-ipa-deployment.yaml, stable/xray/templates/xray-statefulset.yaml
=> [jfrog-platform] 10.19.5 release

stable/distribution/templates/distribution-svc.yaml
Align with Xray svc settings. This is required for hybrid deployments. We are a Enterprise Plus customer.
=> [Distribution] Update distribution-svc.yaml to add http-router port to service

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> [jfrog-platform] 10.20.3 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/values.yaml
=> [jfrog-platform] 10.20.4 release

.gitignore, examples/terraform/jfrog-platform-aws-install/jfrog-platform.tf, examples/terraform/jfrog-platform-aws-install/outputs.tf, examples/terraform/jfrog-platform-aws-install/variables.tf
=> [examples/terraform] Update platform chart to 11.0.1 to support default sizing

.gitignore, examples/terraform/jfrog-platform-aws-install/README.md, examples/terraform/jfrog-platform-aws-install/jfrog-platform.tf, examples/terraform/jfrog-platform-aws-install/jfrog-values.yaml, examples/terraform/jfrog-platform-aws-install/rds.tf, examples/terraform/jfrog-platform-aws-install/variables.tf
=> [examples/terraform] Added support for Catalog , Curation and JAS

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-cpp-ce/values.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/templates/_helpers.tpl, stable/artifactory-ha/templates/rtfs-hpa.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-jcr/values.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory-oss/values.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/templates/_helpers.tpl, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/rtfs-hpa.yaml, stable/artifactory/values.yaml, stable/catalog/CHANGELOG.md, stable/catalog/Chart.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/keys-warnings.yaml, stable/xray/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1963 
=> [artifactory] 7.104.10 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/README.md, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 11.0.3 release

examples/terraform/jfrog-platform-aws-install/README.md, examples/terraform/jfrog-platform-aws-install/rds.tf, examples/terraform/jfrog-platform-aws-install/variables.tf
=> [examples/terraform] Update platform chart to 11.0.3

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml, stable/xray/templates/xray-statefulset.yaml, stable/xray/values.yaml
=> [jfrog-platform] 11.0.4 release

stable/worker/CHANGELOG.md, stable/worker/Chart.yaml, stable/worker/ci/test-values.yaml, stable/worker/templates/_helpers.tpl, stable/worker/templates/deployment.yaml, stable/worker/values.yaml
=> [worker] 1.133.0 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 11.0.6 release

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/ci/xray-disabled-values.yaml, stable/jfrog-platform/sizing/platform-2xlarge.yaml, stable/jfrog-platform/sizing/platform-large.yaml, stable/jfrog-platform/sizing/platform-medium.yaml, stable/jfrog-platform/sizing/platform-small.yaml, stable/jfrog-platform/sizing/platform-xlarge.yaml, stable/jfrog-platform/sizing/platform-xsmall.yaml, stable/jfrog-platform/templates/rabbitmq-creds-secret.yaml, stable/jfrog-platform/templates/rabbitmq-load-definition-secret.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 11.1.2 release

stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 11.1.3 release

examples/terraform/jfrog-platform-aws-install/variables.tf
Update the Terraform example with newer generation instance types
=> Update the terraform example default instances generation

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 11.1.5 release

examples/jfrog-platform/values/values-catalog-jas.yaml
=> [examples] Platform JAS + Catalog enabled values file

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/values.yaml, stable/catalog/CHANGELOG.md, stable/catalog/Chart.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.yaml
=> Jfrog Platform 11.1.8 Release

.gitignore, examples/terraform/jfrog-platform-aws-install/eks.tf, examples/terraform/jfrog-platform-aws-install/metrics.tf, examples/terraform/jfrog-platform-aws-install/providers.tf, examples/terraform/jfrog-platform-aws-install/variables.tf, examples/terraform/jfrog-platform-aws-install/vpc.tf
Fix errors in terraform examples due to major versions breaking compatibility.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2022 
Need to consider supporting the new major modules versions.
=> Pin modules versions to avoid breaking changes

stable/artifactory-cpp-ce/CHANGELOG.md, stable/artifactory-cpp-ce/Chart.yaml, stable/artifactory-ha/CHANGELOG.md, stable/artifactory-ha/Chart.yaml, stable/artifactory-ha/files/nginx-artifactory-conf.yaml, stable/artifactory-ha/templates/artifactory-node-statefulset.yaml, stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml, stable/artifactory-ha/templates/ingress.yaml, stable/artifactory-ha/values.yaml, stable/artifactory-jcr/CHANGELOG.md, stable/artifactory-jcr/Chart.yaml, stable/artifactory-oss/CHANGELOG.md, stable/artifactory-oss/Chart.yaml, stable/artifactory/CHANGELOG.md, stable/artifactory/Chart.yaml, stable/artifactory/files/nginx-artifactory-conf.yaml, stable/artifactory/templates/artifactory-statefulset.yaml, stable/artifactory/templates/ingress.yaml, stable/artifactory/values.yaml, stable/distribution/CHANGELOG.md, stable/distribution/Chart.yaml, stable/distribution/values.yaml, stable/jfrog-platform/CHANGELOG.md, stable/jfrog-platform/Chart.lock, stable/jfrog-platform/Chart.yaml, stable/jfrog-platform/values.yaml
=> [jfrog-platform] 11.2.1 release

stable/catalog/CHANGELOG.md, stable/catalog/Chart.yaml, stable/catalog/files/system.yaml, stable/catalog/values.yaml, stable/xray/CHANGELOG.md, stable/xray/Chart.lock, stable/xray/Chart.yaml, stable/xray/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2029 
=> [Xray] 3.124.20 - Release
