- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
This adds an annotation on the primary/node pods which contains a
checksum of the rendered binarystore.xml. This will ensure that if that
ConfigMap changes, then the pods will restart and apply the changes.
This ensure that if you make changes to the `binarystore.xml` (in the ConfigMap) and run `helm update`, the primary and worker nodes will roll to get those updates.
> Add checksum annotations for the binarystore ConfigMap

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-pdb.yaml
- stable/artifactory-ha/values.yaml
This ensures that during a rolling update of a cluster, one of the
member nodes will always be up serving traffic.
> Adds a PodDisruptionBudget for the member nodes

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/ingress.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/ingress.yaml
- stable/distribution/CHANGELOG.md
- stable/distribution/Chart.yaml
- stable/distribution/templates/ingress.yaml
- stable/mission-control/CHANGELOG.md
- stable/mission-control/Chart.yaml
- stable/mission-control/templates/ingress.yaml
- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/templates/ingress.yaml
Enable using host names beginings with '*' in ingress
**Which issue this PR fixes**
fixes #71 
As it is a minor change, i didn't update the changelog and the version of all charts
> Missing quote for ingress host names in all charts

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/ci/test-values.yaml
- stable/artifactory-ha/requirements.lock
- stable/artifactory-ha/requirements.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/ci/test-values.yaml
- stable/artifactory/requirements.lock
- stable/artifactory/requirements.yaml
Update `postgresql` chart version to 0.9.5.
This is important to be able and use the `postgresConfig` parameter of the `postgresql` chart.
> Update postgresql chart version to 0.9.5

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
When not using the PostgreSQL sub-chart, add support for setting `DB_URL` with `database.url`.
> Support Artifactory db url

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
This PR add the ability to define `artifactory.preStartCommand` for running a command before the entrypoint, which can be used for downloading a custom DB driver to /opt/jfrog/artifactory/tomcat/lib
> Support artifactory.preStartCommand for running command before entrypoint

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
Allow pod anti-affinity settings to include primary node 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #111
> Allow pod anti-affinity settings to include primary node

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/templates/xray-analysis-deployment.yaml
- stable/xray/templates/xray-indexer-deployment.yaml
- stable/xray/templates/xray-persist-deployment.yaml
- stable/xray/templates/xray-server-deployment.yaml
Fix indent of nodeSelector, affinity and tolerations in the templates
Try setting nodeSelector, affinity or tolerations and see it takes affect.
> Fix indent of nodeSelector, affinity and tolerations in the templates

- .github/PULL_REQUEST_TEMPLATE.md
- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/values.yaml
Remove java option `-Dartifactory.locking.provider.type=db`. This is already default setting.
> Remove -Dartifactory.locking.provider.type=db. This is already default

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/templates/xray-server-deployment.yaml
Change the Xray server health probes to look at `/web` so they'll return a 200 and not 300.
This helps supporting running with a GKE ingress controller.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #149
> Xray server support GKE ingress controller with health probes

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/templates/xray-server-deployment.yaml
Fix previous version (0.7.7). Was missing a training `/` for the probes. Now set to `/web/`.
> Xray server support GKE ingress controller with health probes - fix

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
Change the location we copy the `replicator.yaml` to so it will actually be picked up by replicator process.
This is a temporary fix as the Docker image needs to be updated to create symlink `/opt/jfrog/artifactory/replicator` -> `/var/opt/jfrog/artifactory/replicator/`.
Config and data need to be persisted. Application and data+config should be separated.
> Set correct path to replicator.yaml

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
This is purely a documentation change and does not affect the functionality of the chart.
The README.md references a configuration option as `nginx.git` for group ID.
This option should be `nginx.gid` instead. This change corrects that typo.
> Fix typo with nginx configuration options

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-binarystore.yaml
- stable/artifactory-ha/values.yaml
Add support for using [Azure Blob Storage](https://www.jfrog.com/confluence/display/RTF/Configuring+the+Filestore#ConfiguringtheFilestore-AzureBlobStorageClusterBinaryProvider) as binary provider.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #125
> Add support for Azure Blob Storage binary provider

- stable/mission-control/CHANGELOG.md
- stable/mission-control/Chart.yaml
- stable/mission-control/README.md
- stable/mission-control/values.yaml
Avoid OOMKill to java pods by adding 0.5G memory buffer in example resources allocation.
> Add 0.5G memory buffer for java services

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
`terminationGracePeriodSeconds` wasn't set in the correct location, so it wasn't being recognized by the pod.
> Fixes location of terminationGracePeriodSeconds

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-binarystore.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
This chart ports the binarystore feature from the artifactory-ha chart. The reason for doing this is that we have a use case where we have an enterprise license, but wish to deploy without the primary/node setup of the HA chart.
The default binarystore will still use the file-system configuration.
**Which issue this PR fixes**
- fixes #171 
I _believe_ I have made these changes in a backwards compatible way (hence the minor version bump), I'm happy to go to 8.0.0 if this is a large enough change to warrant it.
Also, when I ported the the binarystore config I left the cloudprovider config mostly intact as I wasn't sure what …
> [stable/artifactory] Binarystore configuration for artifactory chart

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/templates/catalina-logger-configmap.yaml
- stable/artifactory-ha/templates/nginx-deployment.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/templates/catalina-logger-configmap.yaml
- stable/artifactory/templates/nginx-deployment.yaml
- stable/artifactory/values.yaml
1. The Artifactory Tomcat logs (`logs/catalina/`) now have an option for sidecar loggers. See `artifactory.catalinaLoggers` in values.yaml.
2. Fix configuration errors in nginx volume name in the loggers
3. Align logger container naming with other charts
> Add support for logger sidecar containers to Artifactory's Tomcat logs

- stable/distribution/CHANGELOG.md
- stable/distribution/Chart.yaml
- stable/distribution/README.md
- stable/distribution/ci/test-values.yaml
- stable/distribution/templates/distribution-statefulset.yaml
- stable/distribution/values.yaml
Add support for running logger sidecar containers to view non default Distribution logs.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #224
> Add support for logger sidecar containers in Distribution

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
Copying the bootstrap configs are currently wired into the postStart. They need to be in the preStart so that they are on the filesystem before artifactory starts up.
No github issue, but support.jfrog.com support ticket #: 100501
David Xu (JFrog) commented in the support ticket that this is indeed backwards behavior.
> copy bootstrap during preStart instead of postStart

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/templates/nginx-deployment.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/templates/nginx-deployment.yaml
- stable/artifactory/values.yaml
Allows users to customise the paths used for the various health probes. I'm adding this as I am attempting to make artifactory webapp run as the ROOT webapp in tomcat. I have everything working, but cannot enable the health probes as they refer to the `/artifactory` endpoint which no longer exists.
Another reason this is potentially useful is that it will allow customising the nginx probe so that if a user wants, they can create a custom healthcheck in the nginx configuration and use that for the readiness probe, while using the artifactory endpoint for liveness. This would allow nginx to go out of service rather than crashlooping when artifactory is unavailable. …
> Custom healthcheck path for artifactory and artifactory-ha

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/templates/xray-analysis-statefulset.yaml
- stable/xray/templates/xray-indexer-statefulset.yaml
- stable/xray/templates/xray-persist-statefulset.yaml
- stable/xray/templates/xray-server-statefulset.yaml
- stable/xray/values.yaml
Switches the management of the Xray components from a `deployment` to a `statefulset`. My reason for wanting to do this is this:
* Currently every new microservice pod is given a unique Id
* microservice uses this unique Id as it's node Id
* microservice registers in Xray with node Id
* Pod eventually dies/gets moved/replaced etc.
* microservice is still registered in Xray, but marked as offline
* Wait a week and the High Availability page in Xray has pages and pages of offline microservices
While this isn't really a problem, I contacted JFrog about this and their recommendation was to set the node Id to something not unique. I figured the easiest way to achieve …
> [stable/xray] Switch to StatefulSet for managing Xray components

- stable/kubexray/CHANGELOG.md
- stable/kubexray/Chart.yaml
- stable/kubexray/templates/deployment.yaml
Prompt the kubexray deployment to roll the pod(s) when the xray_config.yaml changes.
I updated the slack webhook URL, and the pod hasn't reloaded the config. This change should fix that
> Rolling update to kubexray when xray_config.yaml changes

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
Our organization deploys a Helm chart that actually has a dependency on the `artifactory-ha` chart. Now that the Artifactory chart supports user plugins, we'll create the secrets containing the user plugins in our 'wrapper' chart. Since the names of the secrets are named according to the output of template functions, we don't have a hardcoded secret name that we can pass to Artifactory. This PR updates the Artifactory chart to allow the names of externally provided secrets to contain template language …
> Allow secret names for user plugins to contain template language

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-binarystore.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-binarystore.yaml
- stable/artifactory/values.yaml
This PR allows to set the `cacheProviderDir`. As a result, one can use persistent volume claims together with Azure BLOB Storage when settings `cacheProviderDir` and `mountPath` to the same directory.
> Added support for cacheProviderDir

- stable/mission-control/CHANGELOG.md
- stable/mission-control/Chart.yaml
- stable/mission-control/README.md
- stable/mission-control/templates/mission-control-statefulset.yaml
- stable/mission-control/values.yaml
Signed-off-by: Kyle von Bredow <kylevonbredow@gmail.com>
This PR adds support for custom volumes to be mounted into the mission control container.  This will allow the custom init containers to modify the filesystem before mission control runs.  For example, we can add an enterprise CA into the trusted root store, so that mission control can sync to an internally hosted git repository.
> Adding custom volume mounts

- stable/xray/CHANGELOG.md
- stable/xray/README.md
- stable/xray/values.yaml
The embedded mongoDB starts with the default values inherited from the mongoDB chart which has the resources values of (CPU 100m and Memory 250Mi) and (--wiredTigerCacheSizeGB=1) these values will hung mongoDB and the Xray DB sync will error which causes the Xray server pod to crash.
The PR is to suggest resources values that the users can use.
> mongoDB resources documentation

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/access-bootstrap-creds.yaml
- stable/artifactory/values.yaml
Enable the option to add certain IP's that are able to access the access-admin endpoints, where by default only localhost can access with the mentioned user (access-admin).
> option to add IP in access.creds

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/access-bootstrap-creds.yaml
- stable/artifactory-ha/values.yaml
Enable the option to add certain IP's that are able to access the access-admin endpoints, where by default only localhost can access with the mentioned user (access-admin).
> Add the option to provide an IP for the access-admin endpoints

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/values-large.yaml
- stable/xray/values-medium.yaml
- stable/xray/values-small.yaml
- stable/xray/values.yaml
Set the default server and indexer default persistency to true to have better stability and reliability of the DB sync and indexing processes.
A `helm upgrade --force` must be used when upgrading.
> Set server and indexer default persistency to true

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/values.yaml
… when ingress is enabled
Add the ingress.hosts to the nginx server_name directive. This will make sure that the ingress hostnames are able to resolve the repository name from the hostname by the Docker repository sub domain method. This will help users with setting up Docker repository sub domain access without any need to provide a custom values.yaml
> [artifactory-ha] Add ingress.hosts to the Nginx server_name directive when ingress is enabled

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/values.yaml
…enabled
Add the ingress.hosts to the nginx server_name directive. This will make sure that the ingress hostnames are able to resolve the repository name from the hostname by the Docker repository sub domain method. This will help users with setting up Docker repository sub domain access without any need to provide a custom values.yaml
> [artifactory] Add ingress.hosts to the Nginx server_name directive

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
The `artifactory.customVolumeMounts` setting is not currently being applied to the member nodes created by the `artifactory-node-statefulset.yaml` template.  The mounts are only being applied to the primary node.  This adds the mount points to the member nodes as well.
> Add artifactory.customVolumeMounts to member nodes

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/NOTES.txt
Even when masterKey or masterKeySecretName is specified, 
```
***************************************** WARNING ******************************************
* Your Artifactory master key is still set to the provided example:                        *
* artifactory.masterKey=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   *
*                                                                                          *
* You should change this to your own …
```
> Fix masterKey warning render logic in NOTES.txt

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
**What this PR does / why we need it**: In some cases, you must specify the continer resources on k8s platforms managed by the client with specific restrictions. Currently, you can define resources for artifactory primary and node containers. But you can't for the init containers.
**Which issue this PR fixes**: fixes #473
@amithins
@danielezer 
@eldada 
@rimusz
> [artifactory-ha] Provide resources for initContainers

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
**What this PR does / why we need it**:  In some cases, you need to do actions before the predefined init containers such as prepare volume permissions on k8s platforms managed by the client with specific restrictions. Currently, you can define init containers but they are executed after the predefined init containers in Chart.
**Which issue this PR fixes**: fixes #472
@amithins
@danielezer 
@eldada 
@rimusz
> [artifactory-ha] Povide custom init containers before and after predefined init containers

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/templates/xray-analysis-statefulset.yaml
- stable/xray/templates/xray-indexer-statefulset.yaml
- stable/xray/templates/xray-persist-statefulset.yaml
- stable/xray/templates/xray-server-statefulset.yaml
- stable/xray/values.yaml
…init containers using `common.customInitContainersBegin`
This PR adds the option to define custom init containers to be run before the predefined init containers. This was requested by a customer.
> [xray] custom init containers before the predefined init containers

- test/cleaner/install_jamadar.sh
- test/cleaner/jamadar/Chart.yaml
- test/cleaner/jamadar/templates/_helpers.tpl
- test/cleaner/jamadar/templates/configmap.yaml
- test/cleaner/jamadar/templates/deployment.yaml
- test/cleaner/jamadar/templates/rbac.yaml
- test/cleaner/jamadar/values.yaml
- test/cleaner/override-values.yaml
Jamadar check every 6o minutes and deletes namespace older than 24 hours.
It is needed as `chart-releaser` leaves behind resources running if it was timed out.
> add unneeded resources cleaner

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/templates/nginx-deployment.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/templates/nginx-deployment.yaml
- stable/artifactory/values.yaml
**What this PR does / why we need it**:  To have the chance to define custom labels for the nginx deployment and primary & node sateefulset k8s objects
**Which issue this PR fixes**: fixes #505
@amithins
@danielezer 
@eldada 
@rimusz
> [artifactory-ha] - Add custom labels in Nginx deployment and Artifactory statefulset's

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/values.yaml
This PR adds a nodeSelector attribute for Postgresql in the values.yaml file for both the artifactory and artifactory-ha charts. It is possible in a mixed OS node cluster i.e. Windows and Linux, that the Postgresql database would potentially end up being deployed onto a Windows node causing the container not to come online. This change will ensure all of the nodes are deployed to the correct node type:
`helm install --name artifactory-ha jfrog/artifactory-ha --set nodeselector.kubernetes.io/os=linux`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
> Added a nodeSelector subkey to postgresql key

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/values.yaml
Set explicit `postgresql.postgresqlPassword=""` to avoid helm v3 error
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #543
> Set explicit 'postgresql.postgresqlPassword=""' to avoid helm v3 error

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/values.yaml
When using Docker with repository path, a URL with double slash is created, which fails `docker pull` commands.
> Fix creation of double slash in nginx artifactory configuration

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/templates/xray-analysis-statefulset.yaml
- stable/xray/templates/xray-indexer-statefulset.yaml
- stable/xray/templates/xray-persist-statefulset.yaml
- stable/xray/templates/xray-server-statefulset.yaml
- stable/xray/values.yaml
Make the Xray probes customisable 
fixes #542 
@arielkv this PR will make the probes customisable so that you can change the probe to your needs. For example, before a big upgrade, you can change the `initialDelayPeriosSeconds` param to 1 hour. This should be enough to fix your issue, since we can't really change the probe only on upgrade because not all upgrade are as big as you describe and having such a long initial delay would be problematic.
> Make the Xray probes customisable

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-priority-class.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-priority-class.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
Add support for using `PriorityClass` for Artifactory pods. Allows for better protection and scheduling priority.
> Add support for Artifactory PriorityClass

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
Improves the support for setting a custom `artifactory.internalPort`.
- Fix a bug in HA setup
- Improve documentation
- Reduce complexity
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #600 
> Fix support for custom 'artifactory.internalPort'

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-nfs-pvc.yaml
- stable/artifactory-ha/values.yaml
See https://github.com/jfrog/charts/issues/609
Exposes `mountOptions` of NFS PV to values.yaml to make it customizable.
**Which issue this PR fixes**: fixes #609
> Add support for customizable mountOptions of NFS PVs #609

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-service.yaml
…` instead of using `{{ .Release.Name }}`
Change Artifactory service port name to be hard-coded to `http` instead of using `{{ .Release.Name }}`
fixes #639 
> Change Artifactory service port name to be hard-coded

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/values.yaml
Adds `ingress annotations` to set up the base URL of _artifactory_. This is needed when Artifactory is set as the authentication provider, and a client application (e.g. Xray) wants to communicate with it for SSO. The absence of these headers will result in the following response after redirect from Artifactory login:
```json
{ "info": "Failed to exchange token" }
```
More on this issue in [https://jfrog.com/knowledge-base/why-does-my-login-to-xray-ui-fail-with-a-message-error-token-exchange-in-the-browser-after-entering-credentials-during-the-sso-redirect/](https://jfrog.com/knowledge-base/why-does-my-login-to-xray-ui-fail-with-a-message-error-token-exchange-in-the-browser-after-entering-credentials-during-the-sso-redirect/)
> Add artifactory baseurl in ingress annotations

- stable/artifactory-cpp-ce/CHANGELOG.md
- stable/artifactory-cpp-ce/Chart.yaml
- stable/artifactory-cpp-ce/requirements.lock
- stable/artifactory-cpp-ce/requirements.yaml
- stable/artifactory-jcr/CHANGELOG.md
- stable/artifactory-jcr/Chart.yaml
- stable/artifactory-jcr/requirements.lock
- stable/artifactory-jcr/requirements.yaml
- stable/artifactory-oss/CHANGELOG.md
- stable/artifactory-oss/Chart.yaml
- stable/artifactory-oss/requirements.lock
- stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.0.26 (Artifactory 7.2.1)
> Update dependency Artifactory chart version to 9.0.26 (Artifactory 7.2.1)

- stable/artifactory-cpp-ce/CHANGELOG.md
- stable/artifactory-cpp-ce/Chart.yaml
- stable/artifactory-cpp-ce/requirements.lock
- stable/artifactory-cpp-ce/requirements.yaml
- stable/artifactory-jcr/CHANGELOG.md
- stable/artifactory-jcr/Chart.yaml
- stable/artifactory-jcr/requirements.lock
- stable/artifactory-jcr/requirements.yaml
- stable/artifactory-oss/CHANGELOG.md
- stable/artifactory-oss/Chart.yaml
- stable/artifactory-oss/requirements.lock
- stable/artifactory-oss/requirements.yaml
Update dependency Artifactory chart version to 9.0.28 (Artifactory 7.2.1)
> Update dependency Artifactory chart version to 9.0.28 (Artifactory 7.2.1)

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/ci/test-values.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/ci/test-values.yaml
- stable/artifactory/values.yaml
- stable/distribution/CHANGELOG.md
- stable/distribution/Chart.yaml
- stable/distribution/README.md
- stable/distribution/values.yaml
- stable/mission-control/CHANGELOG.md
- stable/mission-control/Chart.yaml
- stable/mission-control/README.md
- stable/mission-control/values.yaml
- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/values-large.yaml
- stable/xray/values-medium.yaml
- stable/xray/values-small.yaml
- stable/xray/values.yaml
Use `postgresqlExtendedConf` for setting custom PostgreSQL configuration (instead of `postgresqlConfiguration`). This will not override core configurations if set, but append to it.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #693 
See [official PostgreSQL chart](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L177)
> Postgresql use postgresqlExtendedConf

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
Fix volume name used by filebeat container. Was wrongly using `volume` instead of `artifactory-volume`.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #718 
> Fix volume name used by filebeat container

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
Three init containers have been added that currently don't respect the `initContainers.resources` value. In an environment where there are default resources this causes the migration pod to be unable to start Artifactory (for example, our default requests/limits are 64Mi mem and 10m CPU).
It's also possible to override the artifactory version that is used in _almost_ every section of the chart, except when the migration script is called. This has been updated to use the same defaulting mechanism used everywhere else
EDIT: I also found that you can't specify an external license secret. The volume was defined twice if you did, so I've fixed that
**Which issue this …
> [artifactory-ha] Add init resources + version customisation for migration pod

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
Fix readme use to `-hex 32` instead of `-hex 16`
> Fix readme use to `-hex 32` instead of `-hex 16`

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/values.yaml
Adds a recommended annotation to values.yaml to avoid 413 errors from the nginx ingress. For us, the ingress was rejecting files as small as 2 MB. 
Additional reading: 
- https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/
- https://www.jfrog.com/jira/browse/RTFACT-9030
> Added ingress annotation to avoid 413 errors.

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/templates/xray-statefulset.yaml
If a user specifies uses the customInitContainer tag in our values.yaml including our example it will fail because of indentation issues.
Found issue today submitting for quick fix as xray chart will not install if this option is used for an init container.
Tag appeared to be missing the ident call like all other similar tags which is root cause of failure.
> xray custominitcontainer template fix for ident issue

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
Custom volume mounts in migration init container to make use of files like postgres SSL certificate which is required on startup
> Custom volume mount for initcontainer

- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
customInitContainers should be executed before the "migration-artifactory" initContainer to adapt use cases like generating the cacerts file for the run time. 
**Which issue this PR fixes**:
Fixes #831
> artifactory: Change custominitContainer order to run before "migration-artifactory"

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/templates/NOTES.txt
If `.Values.xray.masterKeySecretName` was set, `.Values.xray.masterKey`
is still set to `FFFF...` and causes NOTES to print a warning about it.
This commit fixes that, so the incorrect warning is not printed.
Instead of setting `xray.masterKey`, I'm using `xray.masterKeySecretName`, yet the following warning was printed:
```
************************************* WARNING *****************************************
* Your Xray master key is still set to the provided example:                          *
* xray.masterKey=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     *
* …
```
> [ xray ] Fix notes warning regarding master key

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
According to the statefulset yaml files, we check the value of `artifactory.migration.timeoutSeconds`, while the parameters table in the readme had `artifactory.migration.timeout`
> [artifactory]- Fixed typo in README regarding migration timeout

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-service.yaml
Statically set primary service to use service type: ClusterIP. 
This prevents exposing the primary service externally when using type LoadBalancer on a cloud provider.
@danielezer New PR to address the actual issue, thanks for the feedback. Linted and installed and setup as expected.
> [artifactory-ha] Statically setting primary service type to ClusterIP

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/templates/xray-statefulset.yaml
- stable/xray/values.yaml
* Update Xray to version `3.4.0` - https://www.jfrog.com/confluence/display/JFROG/Xray+Release+Notes#XrayReleaseNotes-Xray3.4
* Added Upgrade Notes in README for 3.x upgrades - https://github.com/jfrog/charts/blob/master/stable/mission-control/README.md#special-upgrade-notes
* Bump router version to `1.4.0`
* Bump postgresql tag version to `9.6.18-debian-10-r7`
* Added tpl to support external database secrets values
* Added custom volumes/volumesMounts under `common`
* Removed custom volumes from each specific service
> [xray] 3.4.0 release

- pipelines/ci-rt.yml
- pipelines/pr.yml
Helm v2.16.9 is a companion release to Helm 3.2.4, which had a vulnerability in the handling of plugins. Helm 2 does not have a known security vulnerability. However, we determined that Helm 2 should fail with an error message instead of fixing malformed paths when it detected them. We believe this proactive step will decrease the likelihood of a future vulnerability.
> Bump helm version

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/templates/xray-statefulset.yaml
Currently only 4 out of 5 xray container respect the prestartcommand that is submitted via the values.yaml this will address this issue and now the same mechanism will be used in all 5 out of 5 containers that xray starts in the pod.
Fixed our GKE marketplace issues in partner engineering such as PTRENG-270 Xray IaaS (epic)
This is needed to resolve problems in our GKE marketplace combined artifactory + xray listing as we need xray to "wait" for artifactory to start. By …
> [Xray] Router container prestartcommand implementation/fix

- stable/mission-control/CHANGELOG.md
- stable/mission-control/Chart.yaml
- stable/mission-control/README.md
- stable/mission-control/ci/default-values.yaml
- stable/mission-control/ci/test-values.yaml
- stable/mission-control/templates/mission-control-statefulset.yaml
- stable/mission-control/values.yaml
* Update postgresql tag version to `10.13.0-debian-10-r38`
* Update alpine tag version to `3.12`
* Update busybox tag version to `1.31.1`
* If this is a new deployment or you already use an external database (`postgresql.enabled=false`), these changes **do not affect you**!
* If this is an upgrade and you are using the default PostgreSQL (`postgresql.enabled=true`), you need to pass postgresql.image.tag=9.6.18-debian-10-r7 and databaseUpgradeReady=true
> [mission-control] postgresql 10.x update

- stable/distribution/CHANGELOG.md
- stable/distribution/Chart.yaml
- stable/distribution/ci/default-values.yaml
- stable/distribution/ci/test-values.yaml
- stable/distribution/templates/distribution-statefulset.yaml
- stable/distribution/values.yaml
* Update postgresql tag version to `10.13.0-debian-10-r38`
* Update alpine tag version to `3.12`
*  Update busybox tag version to `1.31.1`
* If this is a new deployment or you already use an external database (`postgresql.enabled=false`), these changes **do not affect you**!
* If this is an upgrade and you are using the default PostgreSQL (`postgresql.enabled=true`), you need to pass postgresql.image.tag=9.6.18-debian-10-r7 and databaseUpgradeReady=true
> [distrubution] postgresql 10.x update

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/ci/default-values.yaml
- stable/xray/ci/test-values.yaml
- stable/xray/requirements.lock
- stable/xray/requirements.yaml
- stable/xray/templates/xray-statefulset.yaml
- stable/xray/values.yaml
* Update postgresql tag version to `10.13.0-debian-10-r38`
* Update alpine tag version to `3.12`
* If this is a new deployment or you already use an external database (`postgresql.enabled=false`), these changes **do not affect you**!
* If this is an upgrade and you are using the default PostgreSQL (`postgresql.enabled=true`), you need to pass postgresql.image.tag=9.6.18-debian-10-r7 and databaseUpgradeReady=true
> [xray] postgresql 10.x update

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/ci/default-values.yaml
- stable/xray/ci/test-rabbitmq-default-values.yaml
- stable/xray/ci/test-rabbitmq-values.yaml
- stable/xray/ci/test-values.yaml
- stable/xray/requirements.lock
- stable/xray/requirements.yaml
- stable/xray/templates/ingress.yaml
- stable/xray/templates/xray-analysis-statefulset.yaml
- stable/xray/templates/xray-indexer-statefulset.yaml
- stable/xray/templates/xray-persist-statefulset.yaml
- stable/xray/templates/xray-server-statefulset.yaml
- stable/xray/templates/xray-setup-conf.yaml
- stable/xray/values.yaml
* Added compatability to support latest 7.x rabbitmq subchart when `rabbitmq.enabled=true`
* Update RabbitMQ chart to v7.4.3
* RabbitMQ 7.x chart is [not compatible](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#to-700) with previous rabbitmq 6.x chart in previous Xray 2.x charts
* Please refer [here](https://github.com/jfrog/charts/blob/pre-unified-platform/stable/xray/README.md#special-upgrade-notes) for upgrade notes
* Add support for Ingress version - `networking.k8s.io/v1beta1` for k8s >= 1.14 using helm v3
**Other info :**
* the networking.k8s.io/v1beta1.Ingress kind was introduced in Kubernetes 1.14.
* the …
> [xray][preunified]Added compatability to support latest 7.x rabbitmq subchart when rabbitmq.enabled=true

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/values.yaml
Postgresql has nodeSelector, affinity and tolerations under master and slave.
Having this in the incorrect place in the Values.yaml file makes it
confusing for people trying to use the chart.
This change is functionally a no-op change. It moves some default postgresql parameters to their correct places. Having the incorrect values is confusing for people deploying the chart because changing the values as they were documented wouldn't actually change anything in the final rendered manifest.
Artifactory, Artifactory-ha and mission-control also have this exact problem, I'll submit PRs for those as soon as we've finished this one.
> [xray] Move postgresql values fields to correct place in Xray Helm chart

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/README.md
- stable/artifactory/values.yaml
Postgresql has nodeSelector, affinity and tolerations under master and slave.
Having this in the incorrect place in the Values.yaml file makes it
confusing for people trying to use the chart.
This change is functionally a no-op change. It moves some default postgresql parameters to their correct places. Having the incorrect values is confusing for people deploying the chart because changing the values as they were documented wouldn't actually change anything in the final rendered manifest.
This change is almost identical to #1005
> [artifactory] Fix postgresql values based on postgresql subchart

- stable/mission-control/CHANGELOG.md
- stable/mission-control/Chart.yaml
- stable/mission-control/README.md
- stable/mission-control/values.yaml
Postgresql has nodeSelector, affinity and tolerations under master and slave.
Having this in the incorrect place in the Values.yaml file makes it
confusing for people trying to use the chart.
I also added postgresql.resources to the README.md file.
This change is functionally a no-op change. It moves some default postgresql parameters to their correct places. Having the incorrect values is confusing for people deploying the chart because changing the values as they were documented wouldn't actually change anything in the final rendered manifest.
This change is almost identical to #1005
> [mission-control] Fix postgresql values based on postgresql subchart

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/README.md
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
Corrects a small typo: _instllations_ -> _installations_
> Fix small typo in README in artifactory-ha

- stable/pipelines/CHANGELOG.md
- stable/pipelines/Chart.yaml
- stable/pipelines/templates/pipelines-statefulset.yaml
Cannot use runAsUser:0 in Openshift for certification with rook-cph 
PTERNG-1120
Required for Pipelines to work in customers Openshift environments
> [Pipelines] Change init container to use CAP_CHOWN 

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/nginx-pvc.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/nginx-pvc.yaml
- stable/artifactory/values.yaml
Value name should be `storageClassName` it is mentioned few lines above in values file, if someone will not notice this litle mistake, PVC will not be assigned to target storage class 
> [artifactory][artifactory-ha] value name change to correct "storageClassName"

- stable/pipelines/CHANGELOG.md
- stable/pipelines/Chart.yaml
- stable/pipelines/templates/pipelines-statefulset.yaml
- stable/pipelines/templates/vault-statefulset.yaml
- stable/pipelines/values.yaml
Changes to use the same name customInitContainerBegin vs customInitBeginContainer per @eldada and @chukka 
PTRENG-1120
Tested w/ all init containers turned on and verified:
kubectl get pods
NAME                                      READY   STATUS    RESTARTS   AGE
artifactory-ha-artifactory-ha-member-0    1/1     Running   0          49m
artifactory-ha-artifactory-ha-primary-0   1/1     Running   0          49m
artifactory-ha-nginx-544d7c9895-hf9r2     1/1     Running …
> [pipelines] Changed to use custominitContainerBegin tag

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
During JFrog Support session w/ customer we had log line warnings about issues with chown:
2)
2020-10-20T20:31:29.468838574Z chown: /opt/jfrog/artifactory: Operation not permitted
2020-10-20T20:31:29.486238263Z 2020-10-20T20:31:29.000Z [shell] [WARN ] [] [installerCommon.sh:706        ] [main] - Could not set owner of [/opt/jfrog/artifactory] to [artifactory:artifactory]
2020-10-20T20:31:29.540815982Z chown: /opt/jfrog/artifactory/var: Operation not permitted
2020-10-20T20:31:29.557993665Z 2020-10-20T20:31:29.000Z [shell] [WARN ] [] [installerCommon.sh:706        ] [main] - Could not set owner of [/opt/jfrog/artifactory/var] to [artifactory:artifactory]
Further …
> [artifactory][artifactory-ha] Artifactory chown log line issue

- stable/mission-control/CHANGELOG.md
- stable/mission-control/Chart.yaml
- stable/mission-control/templates/mission-control-statefulset.yaml
- stable/mission-control/templates/mission-control-svc.yaml
This PR updates all the port names to include a protocol prefix. This is important for installations that would like to use istio as it relies on these prefixes to determine the protocol of the port. (See [here](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/))
I have updated every port that I could find that didn't already have a port name that included the protocol.
There's a 15 character limit on port names, so I had to chomp some …
> [mission-control] Add protocol to port names for istio

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/artifactory-statefulset.yaml
- stable/artifactory/values.yaml
- Adds artifactory.excludeSecurityContext flag to values, defaulted to false
- Adds condition around securityContext block in artifactory-statefulset to exclude if artifactory.excludeSecurityContext is true
This PR exposes a flag in the values.yaml to remove the securityContext block. It has been created as "excludeSecurityContext" and defaulted to `false` to preserve the current default behavior. The securityContext block is removed to allow the chart to install properly on OpenShift clusters.
fixes #1075 …
> Don't merge - [artifactory] Allow securityContext to be removed from statefulset with flag

- stable/pipelines/CHANGELOG.md
- stable/pipelines/Chart.yaml
- stable/pipelines/ci/global-section-values.yaml
- stable/pipelines/templates/pipelines-statefulset.yaml
- stable/pipelines/values.yaml
Adds support for annotations on statefulsets in addition to the pod specs that were already present. This is helpful when interacting with other tooling on the deployment clusters that function via annotations.
This splits out the Pipelines changes from https://github.com/jfrog/charts/pull/1665
> [pipelines] add annotations to statefulset

- stable/distribution/CHANGELOG.md
- stable/distribution/Chart.yaml
- stable/distribution/ci/test-values.yaml
- stable/distribution/templates/distribution-statefulset.yaml
- stable/distribution/values.yaml
Adds support for annotations on statefulsets in addition to the pod specs that were already present. This is helpful when interacting with other tooling on the deployment clusters that function via annotations.
This splits out the Distribution changes from https://github.com/jfrog/charts/pull/1665
> [distribution] add annotations to statefulset

- examples/artifactory/logging/README.md
- examples/artifactory/logging/values-logging-fluent-bit.yaml
An example of how to configure a fluent-bit sidecar for all logs collection in Artifactory using a custom `values-logging-fluent-bit.yaml`
> Add example for fluent-bit sidecar logging

- stable/artifactory-cpp-ce/CHANGELOG.md
- stable/artifactory-cpp-ce/Chart.yaml
- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-ha/ci/small-values.yaml
- stable/artifactory-ha/ci/test-values.yaml
- stable/artifactory-ha/templates/NOTES.txt
- stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
- stable/artifactory-ha/values.yaml
- stable/artifactory-jcr/CHANGELOG.md
- stable/artifactory-jcr/Chart.yaml
- stable/artifactory-oss/CHANGELOG.md
- stable/artifactory-oss/Chart.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/ci/test-values.yaml
- stable/artifactory/templates/NOTES.txt
- stable/artifactory/values.yaml
- stable/jfrog-platform/CHANGELOG.md
- stable/jfrog-platform/Chart.yaml
- stable/jfrog-platform/templates/_helpers.tpl
- stable/jfrog-platform/values.yaml
> [jfrog-platform] 10.15.1 release

- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/templates/nginx-deployment.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/artifactory/templates/nginx-deployment.yaml
Currently, custom labels (`.Values.nginx.labels`) are only added under `metadata.labels`!
Therefore, added custom label support under `template.metadata.labels` as well, so the labels apply to the Nginx pods 🛩️ 
Please let us know if you have any questions!
Thank you for the review!
> [artifactory] Add support for custom labels in the Nginx pods

- stable/xray/CHANGELOG.md
- stable/xray/Chart.yaml
- stable/xray/README.md
- stable/xray/ci/default-values.yaml
- stable/xray/files/system.yaml
- stable/xray/templates/_helpers.tpl
- stable/xray/templates/migration-hook.yaml
- stable/xray/templates/xray-ipa-deployment.yaml
- stable/xray/templates/xray-ipa-svc.yaml
- stable/xray/templates/xray-server-deployment.yaml
- stable/xray/templates/xray-statefulset.yaml
- stable/xray/values.yaml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/jfrog/charts/issues/1895
> [xray] 3.102.3 release

- stable/jfrog-platform/CHANGELOG.md
- stable/jfrog-platform/Chart.yaml
- stable/jfrog-platform/templates/upgrade-hook.yaml
- stable/jfrog-platform/values.yaml
The new pre-upgrade-check pod and container is missing the option to set security context settings. On clusters that require more strict settings the pre-upgrade-check can not be started:
```
violates PodSecurity'
(combined from similar events): Error creating: pods "jfrog-platform-pre-upgrade-check-j527c" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pre-upgrade-check" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pre-upgrade-check" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pre-upgrade-check" must set …
```
> [jfrog-platform] Added podSecurityContext and containerSecurityContext for pre-upgrade-check migration hook container

- stable/artifactory-cpp-ce/CHANGELOG.md
- stable/artifactory-cpp-ce/Chart.yaml
- stable/artifactory-ha/CHANGELOG.md
- stable/artifactory-ha/Chart.yaml
- stable/artifactory-jcr/CHANGELOG.md
- stable/artifactory-jcr/Chart.yaml
- stable/artifactory-oss/CHANGELOG.md
- stable/artifactory-oss/Chart.yaml
- stable/artifactory/CHANGELOG.md
- stable/artifactory/Chart.yaml
- stable/jfrog-platform/CHANGELOG.md
- stable/jfrog-platform/Chart.lock
- stable/jfrog-platform/Chart.yaml
- stable/jfrog-platform/values.yaml
- stable/xray/CHANGELOG.md
- stable/xray/Chart.lock
- stable/xray/Chart.yaml
- stable/xray/ci/default-values.yaml
- stable/xray/files/system.yaml
- stable/xray/templates/catalog-db-create-hook.yaml
- stable/xray/templates/keys-warnings.yaml
- stable/xray/templates/xray-ipa-deployment.yaml
- stable/xray/templates/xray-server-deployment.yaml
- stable/xray/templates/xray-statefulset.yaml
- stable/xray/values.yaml
> [jfrog-platform] 10.20.2 release

- examples/terraform/README.md
- examples/terraform/jfrog-platform-aws-install/README.md
- examples/terraform/jfrog-platform-aws-install/artifactory-license-template.yaml
- examples/terraform/jfrog-platform-aws-install/eks.tf
- examples/terraform/jfrog-platform-aws-install/jfrog-platform.tf
- examples/terraform/jfrog-platform-aws-install/jfrog-values.yaml
- examples/terraform/jfrog-platform-aws-install/metrics.tf
- examples/terraform/jfrog-platform-aws-install/outputs.tf
- examples/terraform/jfrog-platform-aws-install/providers.tf
- examples/terraform/jfrog-platform-aws-install/rds.tf
- examples/terraform/jfrog-platform-aws-install/s3.tf
- examples/terraform/jfrog-platform-aws-install/variables.tf
- examples/terraform/jfrog-platform-aws-install/vpc.tf
Add terraform examples for aws
> Add terraform examples for aws

- stable/artifactory/CHANGELOG.md
- stable/artifactory/values.yaml
Whenever `customIngress` is specified, helm gives a warning about merging incompatible types (string and map).
**Which issue this PR fixes**:
fixes #2020
You can test the change before and after this `values.yaml` change with:
```sh
helm template \
--set customIngress.foo=bar \
--set ingress.enabled=true \
--show-only=templates/ingress.yaml \
--version 107.111.12 \
jfrog/artifactory
helm dependency build stable/artifactory
helm template \
--set customIngress.foo=bar \
--set ingress.enabled=true \
--show-only=templates/ingress.yaml \
./stable/artifactory
```
> [artifactory] fix default value for customIngress so we don't get warnings
